// ============================================================
// KANDANG NDALEM — KELAS MAKRIFAT
// Basis data khazanah tasawuf & kejawen, berlapis kedalaman.
// Empat lapis: syariat (lahir) → tarekat (jalan) → hakikat (inti)
// → makrifat (inti dari inti), lalu diturunkan ke bahasa sehari-hari.
// Seluruh data hidup di berkas ini — tidak ada server, tidak ada awan.
// ============================================================

const KATEGORI = {
  tangga: "Tangga Perjalanan",
  hijab: "Hijab & Penyingkapan",
  puncak: "Puncak & Kemanunggalan",
  jawa: "Khazanah Jawa",
  adab: "Adab & Bekal Jalan",
};

const DATA = [
  // ---------------------------------------------------------- TANGGA
  {
    id: "papat-tataran",
    istilah: "Syariat — Tarekat — Hakikat — Makrifat",
    asal: "Empat tataran jalan (papat tataran)",
    kategori: "tangga",
    alias: ["syariat", "tarekat", "hakikat", "empat tingkat", "papat tataran", "sarengat", "tarekat hakekat", "tingkatan ilmu"],
    kunci: ["tingkat", "tahap", "jalan", "urutan", "kulit", "isi"],
    ringkas: "Empat lapis satu jalan: aturan lahir, laku batin, kenyataan sejati, dan pengenalan langsung.",
    tingkat: {
      syariat: "Syariat adalah tata lahir: shalat, puasa, halal-haram, akhlak kepada sesama. Ia pagar dan wadah. Dalam pepatah pesantren: syariat itu perahu, tarekat samuderanya, hakikat mutiaranya, makrifat adalah lezatnya memandang mutiara itu.",
      tarekat: "Tarekat adalah perjalanan menegakkan yang lahir itu ke dalam: membersihkan niat, menundukkan nafsu, membiasakan dzikir, menjaga hati dari selain Allah. Di sinilah aturan berubah menjadi laku, dan laku menjadi kebiasaan jiwa.",
      hakikat: "Hakikat adalah tersingkapnya kenyataan di balik laku: yang shalat mulai melihat kepada siapa ia berdiri; yang berpuasa mengerti bahwa yang dilaparkan bukan perut melainkan ego. Amal yang sama, tetapi kini tembus pandang.",
      makrifat: "Makrifat adalah pengenalan langsung — bukan tahu tentang Allah, melainkan mengenal Allah. Di sini empat tataran ternyata bukan tangga yang ditinggalkan satu per satu, melainkan satu tubuh: syariat kulitnya, tarekat dagingnya, hakikat tulangnya, makrifat sumsumnya. Kulit yang dibuang membuat sumsum membusuk; sumsum yang tak ada membuat kulit kosong. Al-Ghazali merumuskannya: hakikat tanpa syariat batal, syariat tanpa hakikat kosong.",
    },
    seharihari: "Bayangkan belajar gamelan. Mula-mula kau menghafal aturan pukulan (syariat), lalu berlatih bertahun-tahun sampai tanganmu hafal sendiri (tarekat), lalu suatu hari kau tidak lagi memikirkan aturan — kau dan gending menyatu (hakikat), dan akhirnya kau mengerti untuk apa gending itu dibunyikan sejak awal (makrifat). Pemain yang sudah sampai tidak membuang gamelannya — permainannya justru makin rapi.",
    rujukan: ["Al-Ghazali, Ihya' 'Ulumiddin", "Syekh Amongraga dalam Serat Centhini", "Kitab Sirr al-Asrar (dinisbatkan kpd. Abdul Qadir al-Jailani)"],
  },
  {
    id: "nafs",
    istilah: "Tingkatan Nafsu",
    asal: "an-nafs — النفس; Jawa: hawa napsu papat",
    kategori: "tangga",
    alias: ["nafsu", "nafs", "ammarah", "lawwamah", "muthmainnah", "mutmainah", "supiyah", "aluamah", "amarah", "jiwa"],
    kunci: ["ego", "diri rendah", "hawa", "keinginan", "tujuh tingkat"],
    ringkas: "Peta ego dari yang paling liar sampai yang paling jernih — musuh yang ternyata kendaraan.",
    tingkat: {
      syariat: "Al-Qur'an menyebut tiga wajah nafs: ammarah bis-su' yang menyuruh keburukan (QS 12:53), lawwamah yang mencela diri sendiri (QS 75:2), dan muthmainnah yang tenteram dan dipanggil pulang (QS 89:27–30). Para sufi merincinya hingga tujuh tingkat, sampai kamilah — jiwa paripurna.",
      tarekat: "Kejawen memetakan empat saudara nafsu: aluamah (rakus, gelap), amarah (panas, meledak), supiyah (birahi, ingin dipuji), mutmainah (bening, tenang). Laku suluk bukan membunuh keempatnya — mereka tenaga hidup — melainkan menjinakkan dan mendudukkan masing-masing di tempatnya, seperti kusir menjinakkan empat kuda.",
      hakikat: "Nafsu ternyata bukan musuh dari luar; ia adalah dirimu yang belum matang. Setiap tingkat yang dilampaui bukan dibuang melainkan diserap: keberanian amarah menjadi ketegasan, gairah supiyah menjadi cinta, lapar aluamah menjadi kerinduan. Musuh berubah menjadi tunggangan.",
      makrifat: "Pada puncaknya terlihat: yang selama ini disebut 'aku' hanyalah kumpulan nafsu yang bergiliran memakai namamu. Ketika semuanya jinak dan hening, tinggal satu yang menyaksikan — dan ia bukan nafsu. Nafs muthmainnah dipanggil 'kembalilah kepada Tuhanmu' justru karena ia sudah tidak pergi ke mana-mana.",
    },
    seharihari: "Dirimu seperti rumah yang ramai: ada penghuni yang rakus, yang pemarah, yang haus pujian, yang tenang. Selama ini mereka gantian mengaku-aku sebagai tuan rumah. Laku batin itu sederhana kerjanya: duduk diam, kenali satu per satu suara itu, sampai jelas mana suara penghuni dan mana sang tuan rumah yang sesungguhnya — yang sejak awal hanya memperhatikan.",
    rujukan: ["QS Yusuf 53; QS al-Qiyamah 2; QS al-Fajr 27–30", "Serat Wirid Hidayat Jati", "Al-Qusyairi, ar-Risalah"],
  },
  {
    id: "dzikir",
    istilah: "Dzikir",
    asal: "adz-dzikr — الذكر (ingat)",
    kategori: "tangga",
    alias: ["zikir", "dzikr", "wirid", "ingat allah", "dzikir nafas", "hu allah", "laa ilaaha illallah"],
    kunci: ["ingat", "sebut", "nafas", "lisan", "hati", "sirr"],
    ringkas: "Dari sebutan di lidah, turun ke detak hati, sampai menjadi nafas itu sendiri.",
    tingkat: {
      syariat: "Dzikir lisan: melafalkan kalimat thayyibah — tahlil, tasbih, istighfar — dengan hitungan dan waktu yang dijaga. Lidah dibiasakan basah oleh Nama, sebagaimana wasiat Nabi kepada orang yang merasa syariat terlalu banyak: 'Hendaklah lidahmu selalu basah karena dzikrullah.'",
      tarekat: "Dzikir turun dari lidah ke dada: dzikir qalbi. Kalimat tidak lagi diucapkan tetapi dipukulkan ke hati — dalam tarekat Naqsyabandiyah tanpa suara, dalam Qadiriyah dengan hentakan. Nafas ikut diatur: keluar-masuk udara digandengkan dengan HU–ALLAH, hingga jantung sendiri yang berdzikir ketika lidah tidur.",
      hakikat: "Pada dzikir sirr, yang berdzikir dan yang didzikirkan mulai tak terpisahkan. Bukan lagi 'aku mengingat Allah', melainkan ingat itu sendiri yang menyala terus-menerus tanpa aku yang mengingatnya. Kalimat nafi-itsbat bekerja nyata: laa ilaaha meruntuhkan segala berhala termasuk berhala 'aku', illallah menegakkan satu-satunya yang tinggal.",
      makrifat: "Di puncak, dzikir berbalik arah: kau sadar bukan kau yang mengingat Dia — Dialah yang sejak awal mengingatmu, dan dzikirmu hanyalah gema dari ingatan-Nya: 'Ingatlah Aku, niscaya Aku mengingatmu' (QS 2:152). Nafas yang selama ini kaukira milikmu ternyata pinjaman yang dihembuskan dan ditarik kembali — setiap tarikan nafas adalah Dia menyebutmu.",
    },
    seharihari: "Seperti orang jatuh cinta. Mula-mula ia sengaja menyebut nama kekasihnya (lisan). Lama-lama nama itu terngiang sendiri sepanjang hari (hati). Akhirnya ia tidak perlu menyebut apa-apa — seluruh hidupnya sudah menghadap ke sana, bahkan ketika ia tidur. Dzikir bukan menambah ingatan, tapi membongkar lupa.",
    rujukan: ["QS al-Baqarah 152; QS ar-Ra'd 28", "HR Tirmidzi (lidah basah oleh dzikir)", "Amalan tarekat Qadiriyah-Naqsyabandiyah"],
  },
  {
    id: "khalwat",
    istilah: "Khalwat, 'Uzlah & Riyadhah",
    asal: "khalwah — خلوة (menyepi); Jawa: tapa, semadi",
    kategori: "tangga",
    alias: ["uzlah", "menyepi", "tapa", "semedi", "semadi", "riyadhah", "mujahadah", "tirakat", "puasa batin", "tapa brata"],
    kunci: ["sepi", "sunyi", "latihan", "gua", "hira", "sendiri"],
    ringkas: "Menyepi bukan lari dari dunia, melainkan menutup pintu agar tamu agung bisa masuk.",
    tingkat: {
      syariat: "Nabi sendiri bertahannuts di gua Hira bertahun-tahun sebelum wahyu turun. Khalwat adalah sunnah para pencari: mengurangi bicara, mengurangi makan, mengurangi tidur, mengurangi campur dengan manusia — empat pengurangan yang menjadi pokok riyadhah di hampir semua tarekat, dan menjadi tirakat dalam laku Jawa: mutih, ngebleng, pati geni.",
      tarekat: "Dalam khalwat, dunia yang riuh diputus pasokannya, dan barulah kelihatan betapa riuhnya isi kepala sendiri. Pekerjaan sesungguhnya dimulai di sini: duduk bersama diri sendiri tanpa hiburan, menyaksikan segala keinginan dan ketakutan naik-turun, dan tidak mengikutinya. Mujahadah artinya persis itu — perang melawan gravitasi diri.",
      hakikat: "Yang disepikan sebenarnya bukan tempat, melainkan hati. Ada orang bertapa di gunung tapi pikirannya di pasar; ada orang di pasar tapi hatinya khalwat terus-menerus. Dari sinilah rumusan Naqsyabandiyah: khalwat dar anjuman — menyepi di tengah keramaian. Sunyi yang dicari bukan ketiadaan suara, melainkan ketiadaan tuntutan 'aku'.",
      makrifat: "Puncak khalwat adalah sunyi dari diri sendiri. Selama masih ada yang merasa sedang menyepi, kamar itu masih berisi dua: kau dan kesombongan tapamu. Ketika yang menyepi ikut lenyap, barulah benar-benar kosong — dan dalam kosong itu ternyata tidak pernah ada yang absen: Ia sudah selalu di situ, kaulah yang selama ini ramai.",
    },
    seharihari: "Seperti mau mendengar suara jangkrik: kau harus mematikan televisi dulu. Menyepi itu mematikan televisi batin — gosip, cemas, rencana, dendam — bukan karena dunia jelek, tapi karena ada suara sangat halus yang selama ini kalah keras. Sesudah terlatih, televisi boleh menyala lagi; kau sudah tahu cara mendengar di tengah ramai.",
    rujukan: ["Sirah: tahannuts di Gua Hira", "Al-Ghazali, Ihya' — Kitab 'Uzlah", "Sebelas asas Naqsyabandiyah: khalwat dar anjuman", "Laku tirakat Jawa: Serat Centhini"],
  },
  {
    id: "guru-mursyid",
    istilah: "Guru Mursyid & Sanad",
    asal: "mursyid — مرشد (pemberi petunjuk)",
    kategori: "adab",
    alias: ["mursyid", "guru", "sanad", "silsilah", "bai'at", "baiat", "guru sejati", "wasithah"],
    kunci: ["pembimbing", "izin", "rantai", "adab", "murid"],
    ringkas: "Peta bukan wilayah; buku bukan pembimbing. Jalan curam menuntut kawan yang sudah pernah lewat.",
    tingkat: {
      syariat: "Ilmu diambil dari yang bersanad — rantai guru ke guru sampai ke sumber. Barang siapa berguru tanpa guru, kata pepatah sufi, maka gurunya adalah setan. Bai'at kepada mursyid bukan penyembahan; ia janji setia menempuh jalan, seperti pendaki mengikat diri pada pemandu.",
      tarekat: "Mursyid bekerja seperti cermin dan seperti dokter: ia melihat penyakit hatimu yang tak bisa kaulihat sendiri — sebab mata tidak bisa melihat belek di dirinya sendiri. Resepnya berbeda tiap murid: yang sombong disuruh menyapu, yang kikir disuruh memberi, yang banyak bicara disuruh diam.",
      hakikat: "Guru lahir hanyalah wakil dari Guru batin. Orang Jawa menyebutnya Guru Sejati — pancer yang bersemayam di dalam, yang suaranya halus dan mudah dipalsukan oleh nafsu. Fungsi mursyid justru menajamkan telingamu terhadap Guru Sejati itu dan membongkar setiap pemalsuan; pada akhirnya ia menunjuk ke dalam dirimu, bukan ke dirinya.",
      makrifat: "Yang membimbing sesungguhnya sejak awal hanyalah Allah — al-Hadi, Maha Pemberi Petunjuk. Mursyid, kitab, bahkan pengalaman ruhani hanyalah wasilah, jari yang menunjuk bulan. Tanda guru yang benar: makin lama kau makin tidak bergantung padanya dan makin bergantung pada Allah. Tanda guru palsu: sebaliknya — dan di titik tertinggi pun, adab tetap tinggal: Nabi sendiri di Sidratul Muntaha tetaplah hamba.",
    },
    seharihari: "Belajar menyelam dari buku saja itu bisa — sampai kau kehabisan napas di kedalaman sepuluh meter dan panik. Orang yang sudah ribuan kali menyelam tahu persis rasanya panik itu dan tahu jalan naiknya. Guru bukan untuk disembah dan bukan tempat menyerahkan akal; ia kawan berpengalaman yang menjaga talimu. Dan kalau ada 'guru' yang malah minta talimu diserahkan selamanya — itu bukan pemandu, itu penjual.",
    rujukan: ["Al-Qusyairi, ar-Risalah — bab adab murid", "Serat Wedhatama: ngelmu iku kalakone kanthi laku", "Suluk Linglung Sunan Kalijaga (Guru Sejati)"],
    peringatan: "Kedalaman di kelas ini bukan pengganti pembimbing hidup. Justru para penulis kitab-kitab yang dikutip di sini semuanya menempuh jalan dengan guru.",
  },

  // ---------------------------------------------------------- HIJAB
  {
    id: "hijab",
    istilah: "Hijab — Tujuh Puluh Ribu Tirai",
    asal: "hijab — حجاب (tirai, penutup)",
    kategori: "hijab",
    alias: ["tirai", "penutup", "penghalang", "70000 hijab", "tujuh puluh ribu", "kabut", "warana"],
    kunci: ["tertutup", "terhalang", "cahaya", "kegelapan", "membuka hijab"],
    ringkas: "Yang menutupi Tuhan bukan kegelapan saja — cahaya pun bisa menjadi tirai.",
    tingkat: {
      syariat: "Hadits masyhur di kalangan sufi: 'Allah memiliki tujuh puluh ribu hijab dari cahaya dan kegelapan; seandainya disingkapkan, keagungan Wajah-Nya akan membakar segala yang dipandang-Nya.' Hijab kegelapan adalah dosa, kelalaian, cinta dunia — inilah yang dikikis dengan taubat dan amal.",
      tarekat: "Sesudah hijab gelap menipis, muncul hijab yang lebih licin: hijab cahaya. Kebanggaan atas ibadah, nikmatnya pengalaman ruhani, kedudukan ruhani, ilmu, bahkan kesalehan itu sendiri — semua bisa menjadi tirai baru yang lebih indah dan karenanya lebih sulit dilepas. Perjalanan suluk sesungguhnya adalah penanggalan tirai demi tirai.",
      hakikat: "Kejutan besar para arif: hijab yang terakhir dan paling tebal adalah dirimu sendiri. Bukan dosamu, bukan duniamu — melainkan rasa 'aku ada' yang berdiri di hadapan-Nya sebagai pihak kedua. Selama masih ada yang menonton, tirai belum habis; penonton itulah tirainya.",
      makrifat: "Dan inilah inti dari intinya: hijab tidak pernah menutupi Allah — mustahil sesuatu menutupi Yang Maha Meliputi. Hijab hanya menutupi matamu. Ibn 'Atha'illah berkata dalam al-Hikam: 'Allah tidak terhijab darimu; kaulah yang terhijab dari melihat-Nya.' Maka membuka hijab bukan perjalanan mendekat — jarak itu tidak pernah ada — melainkan berhenti memandang lewat kaca yang kau sebut dirimu. Ia lebih dekat dari urat lehermu (QS 50:16), sejak dulu.",
    },
    seharihari: "Matahari tidak pernah pergi ke mana-mana. Yang membuat kamar gelap adalah gorden — dan gordenmu berlapis-lapis: lapis hitam (dosa, kebencian), lapis berwarna indah (kebanggaan bisa beramal, merasa suci), dan lapis terakhir yang paling aneh: bayanganmu sendiri yang berdiri menghalangi jendela. Membuka hijab bukan menyalakan lampu — cuma menggeser gorden, lalu berhenti berdiri di depan jendela.",
    rujukan: ["Hadits 70.000 hijab (riwayat dalam Misykat al-Anwar)", "Al-Ghazali, Misykat al-Anwar", "Ibn 'Atha'illah, al-Hikam", "QS Qaf 16"],
  },
  {
    id: "fana",
    istilah: "Fana'",
    asal: "fana' — فناء (lebur, sirna)",
    kategori: "hijab",
    alias: ["fana", "lebur", "sirna", "hilang diri", "peleburan", "fana fillah", "musnah"],
    kunci: ["lenyap", "hilang aku", "tenggelam", "larut"],
    ringkas: "Bukan kau yang mati — kepalsuanmu yang gugur. Garam larut ke laut; asinnya tidak hilang.",
    tingkat: {
      syariat: "Secara lahir, fana' tampak dalam amal: fana' dari maksiat karena taat, fana' dari sifat tercela karena akhlak mulia. Seorang hamba yang jujur perlahan kehilangan minat pada apa yang dulu memperbudaknya. Ini fana' tingkat perbuatan — wajib bagi semua, bukan rahasia siapa-siapa.",
      tarekat: "Lalu fana' merambat naik: fana' dari kehendak sendiri ke dalam kehendak-Nya (murid tidak lagi punya proyek pribadi atas hidupnya), fana' dari penglihatan makhluk (pujian dan hinaan manusia terasa sama, karena keduanya lewat begitu saja). Dunia tidak dibenci — ia hanya berhenti menjadi pusat.",
      hakikat: "Fana' sesungguhnya: leburnya kesadaran akan diri di hadapan Yang Hadir. Seperti bintang ketika matahari terbit — bintang tidak dihapus dari langit, tapi cahayanya tenggelam dalam cahaya yang lebih besar. Abu Yazid al-Bisthami menyebut puncaknya fana' 'anil-fana': lebur dari kesadaran bahwa dirinya sedang lebur — sebab yang masih tahu dirinya fana' belum sepenuhnya fana'.",
      makrifat: "Yang paling halus: fana' bukan pencapaian, melainkan pengakuan. Tidak ada yang benar-benar lenyap saat fana' — yang ada hanyalah tersingkapnya kenyataan bahwa 'aku' yang terpisah itu memang tidak pernah ada sejak awal. Kullu man 'alaiha fan (QS 55:26): segala yang di atasnya memang fana' — bukan akan fana', tapi sedang, selalu. Fana' hanyalah saat kau berhenti menyangkalnya.",
    },
    seharihari: "Sebutir garam takut dicelupkan ke laut: 'Aku akan hilang!' Ia dicelupkan — bentuk butirnya memang hilang, tapi asinnya kini seluas samudra. Yang hilang cuma batas yang dikiranya dirinya. Begitu juga 'aku'-mu: yang lebur cuma bungkusnya; isinya justru baru terbebas. Makanya orang yang sudah melewatinya tidak trauma — mereka malah tertawa, kok cuma segini yang dari tadi kutakuti.",
    rujukan: ["QS ar-Rahman 26–27", "Abu Yazid al-Bisthami (riwayat dalam Tadzkiratul Auliya)", "Al-Junayd, Kitab al-Fana'"],
  },
  {
    id: "baqa",
    istilah: "Baqa'",
    asal: "baqa' — بقاء (kekal, tinggal)",
    kategori: "hijab",
    alias: ["baqa", "kekal", "baqa billah", "tinggal bersama", "hidup kembali"],
    kunci: ["sesudah fana", "kembali", "turun gunung", "hidup baru"],
    ringkas: "Sesudah lebur, dikembalikan — tapi yang pulang bukan lagi orang yang dulu berangkat.",
    tingkat: {
      syariat: "Tanda baqa' justru sangat membumi: orang itu kembali bekerja, berkeluarga, berdagang, mengajar — dan syariatnya makin rapi, bukan makin longgar. Para nabi dan wali besar semua hidup dalam baqa': Muhammad ﷺ kembali dari Sidratul Muntaha untuk memimpin pasar dan perang, bukan untuk menetap di langit.",
      tarekat: "Fana' yang dibiarkan berlarut membuat orang mabuk dan lumpuh (sukr). Baqa' adalah kesadaran yang dikembalikan (sahw) — tapi kini kesadaran itu bening: bertindak tanpa pamrih, mencintai tanpa mencengkeram, bekerja tanpa gelisah hasil. Al-Junayd menyebut ini akhir yang kembali ke awal: 'Akhir perjalanan adalah kembali ke permulaan' — hamba kembali jadi hamba, tapi kini sungguh-sungguh hamba.",
      hakikat: "Dalam baqa', dua kenyataan dipegang sekaligus tanpa saling membatalkan: ia sadar dirinya hamba yang fakir, dan sadar bahwa yang bergerak melalui dirinya adalah Dia. Seperti bulan: tahu persis dirinya batu gelap, dan justru karena itu sempurna memantulkan matahari. Inilah maqam 'abduhu — dan kehambaan ternyata lebih tinggi dari segala klaim ketuhanan.",
      makrifat: "Rahasia baqa': fana' dan baqa' bukan dua babak yang berurutan, melainkan dua sisi satu keping yang berlangsung serentak selamanya. Setiap kejap, segala sesuatu lebur ke dalam-Nya dan ditegakkan kembali oleh-Nya — 'Setiap saat Dia dalam kesibukan' (QS 55:29). Orang makrifat hidup di denyut itu: mati-hidup, mati-hidup, pada setiap tarikan nafas. Karena itu ia tidak takut mati — ia sudah mati dan dihidupkan ribuan kali sehari.",
    },
    seharihari: "Seperti orang yang selamat dari sakit yang hampir merenggutnya: sesudahnya ia tetap ke pasar, tetap masak, tetap kerja — tapi caranya memandang semua itu berubah total. Ia tidak lagi cemas hal kecil, tidak lagi genggam apa pun terlalu erat, dan anehnya jadi lebih hangat, lebih hadir. Dari luar tampak biasa saja; di dalamnya sudah berganti pemerintahan.",
    rujukan: ["QS ar-Rahman 29", "Al-Junayd (sahw sesudah sukr)", "Al-Qusyairi, ar-Risalah — bab fana' & baqa'"],
  },
  {
    id: "mati-sajroning-urip",
    istilah: "Mati Sajroning Urip",
    asal: "Jawa: mati di dalam hidup; mutu qabla an tamutu",
    kategori: "jawa",
    alias: ["mati sakjeroning urip", "mati sadurunge mati", "mati sebelum mati", "mutu qabla", "urip sajroning mati", "mati raga"],
    kunci: ["kematian", "ego mati", "hidup sejati", "latihan mati"],
    ringkas: "Matilah sebelum engkau mati — agar saat kematian datang, ia menjemput orang yang sudah selesai.",
    tingkat: {
      syariat: "Ungkapan sufi masyhur 'mutu qabla an tamutu' — matilah sebelum kalian mati. Lahirnya: banyak mengingat kematian, ziarah kubur, hidup sederhana, menyiapkan amal — sebagaimana wasiat Nabi bahwa mengingat mati mencairkan hati yang keras.",
      tarekat: "Lakunya: mematikan gejolak sebelum gejolak mematikanmu. Dalam istilah Jawa, mati raga — raga tetap hidup dan bekerja, tapi tuntutan-tuntutannya tidak lagi memerintah. Tersinggung tapi tidak membalas, ingin tapi bisa tidak, dipuji tapi tidak mengembang: setiap kemenangan kecil itu adalah satu kematian kecil sang ego.",
      hakikat: "Yang dimaksud mati di sini adalah matinya klaim kepemilikan: mati dari 'hartaku', 'nama baikku', 'pendapatku', 'hidupku'. Yang tersisa sesudah semua 'ku' itu tanggal bukanlah mayat, melainkan hidup yang jauh lebih deras — urip sajroning mati, hidup sejati di dalam kematian ego. Kematian badan kelak hanya formalitas bagi orang yang sudah menempuh kematian ini.",
      makrifat: "Inti terdalamnya: yang bisa mati memang harus mati, supaya terbukti mana yang tidak bisa mati. Tubuh, pikiran, perasaan, peran — semua fana. Sesudah semuanya diserahkan, tinggal Sang Hidup — al-Hayy — yang tidak pernah lahir dan karenanya tidak bisa mati. Orang Jawa menyebut yang tinggal itu urip sejati; ia bukan milikmu — kaulah yang sejak awal dipinjami-Nya. Mati sajroning urip adalah mengembalikan pinjaman selagi tanganmu masih bisa menyerahkan.",
    },
    seharihari: "Seperti melunasi utang sebelum ditagih. Semua orang akhirnya menyerahkan segalanya saat mati — harta, nama, badan. Yang menyedihkan kalau semuanya direnggut paksa dalam keadaan masih digenggam erat. Yang lega kalau sudah diserahkan baik-baik dari sekarang: badan dirawat tapi tidak disembah, nama dijaga tapi tidak dibela mati-matian. Orang seperti ini susah diancam — mau diancam kehilangan apa? Dia sudah menyerahkan semuanya duluan.",
    rujukan: ["Ungkapan sufi: mutu qabla an tamutu", "Suluk Sujinah; Serat Wedhatama", "HR Tirmidzi: perbanyak mengingat pemutus kelezatan"],
  },
  {
    id: "suwung",
    istilah: "Suwung",
    asal: "Jawa: kosong, sepi, hampa yang penuh",
    kategori: "jawa",
    alias: ["kosong", "sepi", "hampa", "awang uwung", "sunya", "sunyata", "hening"],
    kunci: ["kekosongan", "hening", "tan kena kinaya ngapa", "sebelum ada"],
    ringkas: "Kosong yang bukan tidak ada — melainkan penuh yang tak tertampung oleh bentuk apa pun.",
    tingkat: {
      syariat: "Dalam tembang dan suluk Jawa, sebelum jagat digelar yang ada hanyalah awang-uwung — hampa tanpa arah, tanpa atas-bawah. Ini sejalan dengan hadits qudsi yang dicintai para sufi: 'Aku adalah perbendaharaan tersembunyi; Aku rindu dikenali, maka Kuciptakan makhluk agar mereka mengenal-Aku.'",
      tarekat: "Lakunya: mengosongkan. Gelas penuh tidak bisa dituangi. Meditasi Jawa (maneges, semadi) dan diam para sufi sama-sama bekerja mengosongkan wadah — dari rencana, dari tafsir, dari keinginan mengalami sesuatu yang hebat. Suwung tidak bisa dikejar; ia yang tersisa ketika pengejarnya capek dan berhenti.",
      hakikat: "Suwung bukan lawan dari isi — ia rahim segala isi. Seperti keheningan yang bukan musuh musik melainkan kanvas tempat semua nada berdiri; seperti layar yang tak terlihat justru karena semua gambar terjadi di atasnya. Para arif Jawa menyebut Yang Mutlak itu tan kena kinaya ngapa — tak bisa diserupakan dengan apa pun — bukan karena Dia kurang, tapi karena setiap rupa terlalu sempit.",
      makrifat: "Inti dari intinya: suwung sejati bukan pengalaman kosong yang kau capai — sebab kalau masih ada yang mengalami, itu belum suwung. Ia adalah wajah dari laisa kamitslihi syai' (QS 42:11): tidak ada sesuatu pun yang menyerupai-Nya. Setiap gambaran tentang Tuhan yang bisa kau bayangkan pasti bukan Dia; maka jalan terakhir bukan menambah gambaran melainkan menanggalkan semuanya — dan yang tinggal ketika semua gambar tanggal bukanlah ketiadaan, melainkan Yang Maha Ada tanpa perantara gambar. Kosong di puncak ternyata Maha Penuh.",
    },
    seharihari: "Layar bioskop tidak pernah kelihatan selama film bagus — semua mata menonton gambarnya. Padahal tanpa layar, tak ada satu gambar pun bisa tampil. Suwung itu belajar melihat layarnya: bukan menolak filmnya, cuma sadar bahwa yang menampung segala cerita itu sendiri tidak ikut jadi cerita. Pikiran kosong sesaat sebelum tidur, jeda hening di antara dua nafas — itu celah kecilnya, gratis, tersedia tiap hari.",
    rujukan: ["Hadits qudsi Kanzun Makhfiy (perbendaharaan tersembunyi)", "QS asy-Syura 11", "Serat Sastra Gendhing; suluk-suluk pesisiran"],
  },
  {
    id: "lathaif",
    istilah: "Lathaif — Anatomi Batin",
    asal: "lathifah — لطيفة (titik halus), jamak: lathaif",
    kategori: "hijab",
    alias: ["lathifah", "latifah", "qalb", "ruh", "sirr", "khafi", "akhfa", "fuad", "lubb", "anatomi ruhani", "titik halus"],
    kunci: ["hati", "ruh", "rahasia", "dada", "peta batin", "tujuh titik"],
    ringkas: "Peta tubuh halus para sufi: dari dada yang lapang sampai rahasia di dalam rahasia.",
    tingkat: {
      syariat: "Al-Qur'an sendiri memakai peta bertingkat untuk batin manusia: shadr (dada — QS 39:22), qalb (hati — QS 22:46), fu'ad (hati terdalam — QS 53:11), lubb (inti akal — QS 3:190). Ini bukan hiasan bahasa; tiap kata menunjuk kedalaman yang berbeda, seperti kulit, daging, dan biji pada satu buah.",
      tarekat: "Tarekat Naqsyabandiyah merinci lathaif menjadi titik-titik yang 'disiram' dzikir satu per satu: qalb (jantung ruhani), ruh, sirr (rahasia), khafi (tersembunyi), akhfa (paling tersembunyi), ditambah nafs dan seluruh jasad. Murid berdzikir menyalakan titik demi titik seperti menyalakan lampu ruangan demi ruangan menuju kamar paling dalam.",
      hakikat: "Makin ke dalam, makin bukan 'milikmu'. Qalb masih bisa bolak-balik (arti harfiah qalb: yang berbalik-balik), tapi sirr adalah titik temu yang hanya diketahui Allah dan hamba — rahasia yang bahkan malaikat pencatat tak membacanya. Para sufi berkata: sirr-ku adalah rahasia-Ku; hanya Kutitipkan pada hamba yang Kucintai.",
      makrifat: "Di titik terdalam (akhfa — paling tersembunyi), peta berhenti berguna: sebab yang ditemukan di kamar terakhir bukan sesuatu, melainkan Yang selama ini menyalakan semua lampu. Perjalanan ke dalam ternyata bukan perjalanan menuju Dia, melainkan perjalanan menghabiskan semua yang bukan Dia. Kamar terakhir tidak punya dinding.",
    },
    seharihari: "Seperti rumah Jawa: ada pendopo tempat semua tamu boleh duduk (dada — emosi sehari-hari), pringgitan yang lebih dalam (hati — cinta, iman), ndalem tempat keluarga inti (fuad — keyakinan yang tak goyah), dan senthong tengah — kamar paling dalam yang bahkan anak-anak jarang masuk (sirr — rahasiamu dengan Tuhan saja). Kenali rumahmu sendiri: banyak orang seumur hidup hanya tinggal di pendopo.",
    rujukan: ["QS az-Zumar 22; al-Hajj 46; an-Najm 11; Ali 'Imran 190", "Ajaran lathaif Naqsyabandiyah-Mujaddidiyah", "Al-Hakim at-Tirmidzi, Bayan al-Farq"],
  },
  {
    id: "kasyf",
    istilah: "Kasyf & Musyahadah",
    asal: "kasyf — كشف (tersingkap); musyahadah — penyaksian",
    kategori: "hijab",
    alias: ["kasyaf", "tersingkap", "penyingkapan", "musyahadah", "penyaksian", "terbuka mata batin", "weruh sadurunge winarah"],
    kunci: ["melihat", "mata batin", "ilham", "penglihatan ruhani"],
    ringkas: "Tersingkapnya penglihatan batin — anugerah yang datang sesudah kaca hati digosok, bukan dikejar.",
    tingkat: {
      syariat: "Kasyf tidak dicari dan tidak dijadikan hujjah hukum. Timbangan tetap Al-Qur'an dan Sunnah: penyingkapan sejati tidak pernah bertentangan dengan keduanya. Para masyayikh keras di sini — Abu Yazid berkata: jika kalian lihat orang bisa terbang dan berjalan di atas air, jangan tertipu sebelum kalian timbang ia dengan syariat.",
      tarekat: "Hati itu cermin; kasyf hanyalah akibat dari cermin yang bersih. Maka pekerjaan murid bukan mengejar penglihatan, melainkan menggosok karat: takhalli. Penglihatan yang datang saat cermin masih kotor justru berbahaya — bisa jadi pantulan nafsu sendiri atau permainan waham yang mengenakan jubah cahaya.",
      hakikat: "Kasyf yang sejati bukan melihat hal-ajaib, melainkan melihat hal-biasa sebagaimana adanya: melihat bahwa rezeki memang selalu cukup, bahwa setiap kejadian memang tepat, bahwa tidak ada yang kebetulan. Musyahadah puncaknya sebagaimana definisi ihsan: menyembah Allah seakan engkau melihat-Nya — dan bila belum bisa melihat-Nya, sungguh Dia melihatmu; dua sayap satu penyaksian.",
      makrifat: "Rahasia terakhirnya: yang disingkap oleh kasyf tertinggi bukanlah pemandangan baru, melainkan si pemandang itu sendiri. Selama masih ada 'aku yang menyaksikan Dia', penyaksian masih berjarak. Musyahadah paripurna adalah ketika terbukti yang menyaksikan dan yang disaksikan tidak pernah dua — Dialah asy-Syahid dan al-Masyhud sekaligus, dan 'kau' hanyalah tempat penyaksian itu berlangsung.",
    },
    seharihari: "Jendela berdebu membuat pemandangan buram — kau tidak perlu menciptakan pemandangan baru, cukup mengelap kacanya. Firasat ibu tentang anaknya, tahu sebelum diberi tahu (weruh sadurunge winarah), tenang aneh sebelum kabar buruk — itu kilasan-kilasan jendela yang sedang bening. Jangan dikejar dan jangan dipamerkan; makin dikejar makin buram, karena yang mengejar itulah debunya.",
    rujukan: ["Hadits Jibril: definisi ihsan", "Al-Qusyairi, ar-Risalah — bab kasyf", "Al-Hujwiri, Kasyful Mahjub"],
  },

  // ---------------------------------------------------------- PUNCAK
  {
    id: "makrifat",
    istilah: "Makrifat",
    asal: "ma'rifah — معرفة (pengenalan langsung)",
    kategori: "puncak",
    alias: ["marifat", "ma'rifat", "makripat", "mengenal allah", "pengenalan", "arif", "gnosis"],
    kunci: ["kenal", "tahu rasa", "ilmu rasa", "ngelmu rasa", "puncak ilmu"],
    ringkas: "Bukan tahu tentang Dia — melainkan kenal. Sebagaimana beda membaca resep dan mencicipi masakan.",
    tingkat: {
      syariat: "Man 'arafa nafsahu faqad 'arafa Rabbahu — siapa mengenal dirinya, mengenal Tuhannya. Pintu makrifat yang paling lahir: mengenali diri sebagai hamba — lemah, fakir, bergantung — sehingga mengenal Rabb sebagai Yang Kuat, Kaya, Tempat Bergantung. Ilmu tauhid yang dipelajari adalah kerangkanya.",
      tarekat: "Makrifat tumbuh dari laku, bukan dari bacaan — orang Jawa menyebutnya ngelmu rasa, ilmu yang masuk lewat rasa sesudah dijalani. Al-Ghazali membedakannya seperti orang yang tahu definisi mabuk dan orang yang pernah mabuk: yang pertama punya keterangan, yang kedua punya pengenalan. Setiap dzikir, sabar, syukur yang dijalani menambah satu tetes rasa itu.",
      hakikat: "Makrifat sejati menjungkirbalikkan arah panah: bukan hamba yang berhasil mengenal Allah dengan usahanya — akal dan indera tak akan sampai — melainkan Allah yang memperkenalkan Diri kepada hamba yang wadahnya siap. Karena itu para arif berkata: 'Aku mengenal Tuhanku dengan Tuhanku.' Usahamu hanyalah menyiapkan tanah; hujan turun dari sana.",
      makrifat: "Puncak makrifat justru pengakuan agung ketidaktahuan: al-'ajzu 'an darkil-idraki idrak — ketaksanggupan menjangkau pengenalan itulah pengenalan. Abu Bakar ash-Shiddiq mengucapkannya, para arif mengulangnya. Yang dikenal Allah lewat makrifat bukanlah hakikat Dzat-Nya — samudra tak tertampung gelas — melainkan tersingkapnya kenyataan bahwa gelas itu sendiri sejak awal berada di dalam samudra, dibuat dari air samudra, dan tak pernah sedetik pun di luarnya. Arif tertinggi adalah yang paling tahu bahwa ia tidak tahu — dan justru di situ ia paling dekat.",
    },
    seharihari: "Kau bisa hafal biografi seseorang, tinggi badannya, tanggal lahirnya — itu 'tahu tentang'. Beda dengan sahabat yang duduk bersamanya bertahun-tahun: ia mungkin tak hafal data, tapi sekali dengar langkah kakinya di kejauhan ia langsung tahu — itu 'kenal'. Makrifat adalah pindah dari hafal data tentang Tuhan menjadi kenal — dan kenal tidak bisa dipelajari lewat buku ini pun; buku hanya alamat rumah, kenalnya harus datang sendiri.",
    rujukan: ["Ungkapan man 'arafa nafsahu (masyhur di kalangan sufi)", "Al-Ghazali, Ihya' & al-Munqidz min adh-Dhalal", "Dzun Nun al-Mishri tentang makrifat"],
  },
  {
    id: "wahdatul-wujud",
    istilah: "Wahdatul Wujud & Wahdatus Syuhud",
    asal: "wahdat al-wujud — وحدة الوجود (kesatuan wujud)",
    kategori: "puncak",
    alias: ["wahdatul wujud", "kesatuan wujud", "wahdat", "ibn arabi", "wahdatus syuhud", "sirhindi", "panteisme", "wujud tunggal"],
    kunci: ["satu wujud", "semua adalah dia", "tajalli", "bayangan", "cermin"],
    ringkas: "Hanya ada satu Wujud sejati; selebihnya bayangan-Nya di cermin ketiadaan. Dan koreksi halusnya: satu dalam penyaksian.",
    tingkat: {
      syariat: "Landasannya tauhid yang dikenal semua muslim: laa ilaaha illallah, dan Huwal-Awwalu wal-Akhiru wazh-Zhahiru wal-Bathin — Dia Yang Awal, Yang Akhir, Yang Lahir, Yang Batin (QS 57:3). Ibn 'Arabi tidak pernah mengajarkan makhluk itu Tuhan; ia mengajarkan bahwa wujud makhluk adalah pinjaman, seperti terang bulan yang seluruhnya milik matahari.",
      tarekat: "Dalam perjalanan, paham ini bukan teori tapi terapi: setiap kali kau melihat kelebihan pada makhluk — kecantikan, kekuasaan, ilmu — segera kembalikan kepada Pemiliknya. Latihan menyaksikan Yang Satu di balik yang banyak inilah yang mengikis iri, takut, dan silau kepada makhluk: bagaimana silau kepada bayangan bila sudah kenal Pemilik bayangan?",
      hakikat: "Ibn 'Arabi: alam semesta adalah tajalli — penampakan terus-menerus Allah pada cermin-cermin kemungkinan; tak pernah berulang dua kali, la takrar fit-tajalli. Sirhindi mengoreksi dengan wahdatus syuhud: yang satu itu penyaksianmu, bukan wujudnya — di puncak mabuk, salik melihat semua adalah Dia; sesudah sadar, ia tahu makhluk tetap makhluk, hanya saja tembus cahaya. Dua rumus ini bukan musuh: yang satu memotret dari puncak, yang lain memotret jalan pulangnya.",
      makrifat: "Inti yang tak boleh tergelincir: 'semua adalah Dia' dan 'tak ada yang menyerupai-Nya' harus dipegang serentak. Kalau kau berhenti di 'alam adalah Tuhan', kau jatuh ke panteisme — Tuhan habis dibagi ke dalam benda. Para arif memegang tanzih dan tasybih sekaligus: Dia Maha Lain dari segalanya, dan tak ada yang tampil kecuali dari-Nya. Seperti samudra dan ombak: ombak bukan samudra (ia cuma bentuk sesaat), tapi coba tunjuk bagian ombak yang bukan air samudra. Yang tidak pernah ada hanyalah ombak yang berdiri sendiri.",
    },
    seharihari: "Uang kertas seratus ribu: kertasnya sendiri tak bernilai — nilainya 'dititipkan' oleh negara. Seluruh alam seperti itu: keberadaannya dititipkan setiap saat oleh Yang Maha Ada. Bukan berarti kertas itu negara — tapi tanpa negara, ia cuma kertas. Maka orang arif memandang segala hal dengan dua mata sekaligus: mata yang melihat kertas (makhluk), dan mata yang melihat nilai yang menopangnya (Wujud yang meminjaminya ada). Dua mata terbuka — itu baru melihat utuh.",
    rujukan: ["QS al-Hadid 3", "Ibn 'Arabi, Fushush al-Hikam & Futuhat Makkiyah", "Ahmad Sirhindi, Maktubat", "Abdurrauf as-Singkili & Nuruddin ar-Raniri (perdebatan wujudiyah Nusantara)"],
  },
  {
    id: "manunggaling",
    istilah: "Manunggaling Kawula Gusti",
    asal: "Jawa: menyatunya hamba dan Tuhan",
    kategori: "puncak",
    alias: ["manunggal", "kawula gusti", "jumbuhing kawula gusti", "pamoring kawula gusti", "curiga manjing warangka"],
    kunci: ["menyatu", "persatuan", "hamba dan tuhan", "keris dan sarung"],
    ringkas: "Keris masuk ke sarungnya: dua nama, satu kenyataan. Ajaran yang membuat Siti Jenar dihukum — dan tetap hidup lima abad kemudian.",
    tingkat: {
      syariat: "Secara lahir, batasnya tegas dan para wali sepakat: hamba tetap hamba, Gusti tetap Gusti. Sultan Agung dalam Sastra Gendhing dan para pujangga keraton memakai istilah ini dengan pagar: pamoring kawula Gusti — berpadunya, bukan berubahnya hamba menjadi Tuhan. Shalat tidak gugur, adab tidak runtuh.",
      tarekat: "Lakunya adalah meniadakan jarak sikap: kehendak hamba dilatih larut ke kehendak Gusti — sumarah (berserah), sumeleh (meletakkan diri), nrima ing pandum (menerima bagian) — sampai tidak ada lagi 'maunya sendiri' yang bertabrakan dengan takdir. Persatuan dimulai bukan di angan metafisika, tapi di dapur: rela, sabar, ikhlas.",
      hakikat: "Lambangnya curiga manjing warangka — keris masuk sarungnya; dan dibalik: warangka manjing curiga — sarung masuk ke keris. Hamba tenggelam dalam Tuhan, dan Tuhan menampakkan diri melalui hamba. Yang bersatu bukan dua dzat menjadi satu dzat — melainkan tersingkapnya bahwa yang kedua tak pernah punya wujud sendiri. Sebagaimana ombak 'bersatu' dengan samudra: bukan peristiwa baru, hanya pengakuan atas yang sejak awal benar.",
      makrifat: "Inilah yang diperkarakan pada Siti Jenar: ia menyebut kesadaran itu dengan bahasa telanjang di depan umum, dan tatanan menjawab dengan hukuman. Inti dari intinya: manunggal bukanlah hamba naik pangkat jadi Tuhan — itu justru puncak kesombongan ego. Manunggal adalah hamba habis; yang tinggal hanya Gusti. Selama masih ada yang mengaku 'aku sudah manunggal', persatuan belum terjadi — sebab masih ada dua: Gusti dan si pengaku. Karena itu para arif sejati justru makin bungkam dan makin membungkuk: bukti persatuan bukan pengakuan, melainkan lenyapnya yang mengaku.",
    },
    seharihari: "Besi dimasukkan ke bara: lama-lama ia membara — menyala, panas, memerah seperti api. Bolehkah besi berkata 'aku api'? Rasanya memang begitu; tapi begitu dikeluarkan, ia besi lagi. Yang bijak, besi itu diam, menikmati baranya, dan membiarkan panasnya menghangatkan orang lain. Kalau kau di puncak rasa menyatu — tak perlu diumumkan. Diumumkan malah jadi dingin: yang sibuk mengumumkan tidak sedang di dalam bara.",
    rujukan: ["Serat Sastra Gendhing (Sultan Agung)", "Babad & Serat Siti Jenar (pelbagai versi)", "Al-Ghazali, Misykat al-Anwar (analogi besi & api)"],
    peringatan: "Sejarah mencatat: kalimat puncak yang diucapkan di pasar menuai perkara — pada al-Hallaj di Baghdad maupun Siti Jenar di Jawa. Para wali menyimpannya bukan karena pelit, melainkan karena sayang: susu murni menyehatkan bayi yang siap, dan menyakiti perut yang belum.",
  },
  {
    id: "ana-al-haqq",
    istilah: "Ana al-Haqq & Syathahat",
    asal: "ana al-haqq — أنا الحق (Akulah Yang Maha Benar)",
    kategori: "puncak",
    alias: ["ana al haq", "al hallaj", "syathahat", "syatahat", "shathiyat", "inani ana allah", "ucapan ekstase", "subhani"],
    kunci: ["hallaj", "mabuk", "ekstase", "ucapan puncak", "aku kebenaran"],
    ringkas: "Ucapan yang meluap saat 'aku' sedang tenggelam — dipahami para arif, diperkarakan pasar, dibayar al-Hallaj dengan nyawa.",
    tingkat: {
      syariat: "Tahun 922 M, Husain ibn Manshur al-Hallaj dihukum mati di Baghdad — perkaranya berlapis politik, tapi yang dikenang adalah kalimatnya: Ana al-Haqq. Secara syariat, kalimat itu tidak boleh dijadikan akidah atau ditiru: al-Haqq adalah nama Allah, dan makhluk bukan Allah. Para imam sufi sendiri — Junayd gurunya — tidak membenarkannya diucapkan terbuka.",
      tarekat: "Para masyayikh menggolongkannya syathahat: luapan kata dalam keadaan sukr (mabuk ruhani), ketika kesadaran diri sedang tenggelam total. Seperti orang tenggelam yang berteriak — itu bukan pernyataan ilmiah tentang air. Kaidahnya: syathahat dimaafkan bagi pengucapnya yang tenggelam, tidak dijadikan dalil bagi yang sadar, dan tidak ditiru oleh yang belum sampai. Meniru ucapan mabuk dalam keadaan sadar bukan makrifat — itu dusta.",
      hakikat: "Yang terjadi menurut para arif: pada puncak fana', 'aku' al-Hallaj sedang tidak ada; yang bicara bukan Husain. Sebagaimana semak di Thursina menyuarakan 'Inni ana Allah — sesungguhnya Akulah Allah' (QS 20:14) kepada Musa — bukan semak yang mengaku Tuhan, melainkan Tuhan bersuara melewati semak. Rumi menutup perkaranya dengan halus: justru berkata 'aku hamba' bisa lebih sombong — sebab masih menegakkan 'aku' di samping Allah; sedangkan Ana al-Haqq Hallaj adalah pengakuan bahwa dirinya tidak ada sama sekali.",
      makrifat: "Inti dari intinya: kalimat itu benar dari sisi Yang berbicara, dan salah dari sisi yang mengulanginya. Ketika kau — yang sedang sadar, utuh, punya nama dan rekening — mengucapkan 'akulah Allah', maka 'aku' yang kau maksud adalah egomu, dan itu kebalikan total dari yang dialami Hallaj: ia diucapkan justru saat ego hangus. Maka ujian kejujurannya sederhana: yang benar-benar lebur tidak butuh mengumumkan, sebab tak ada lagi yang butuh diakui. Kerinduanmu pada kalimat itu selami sebagai kerinduan pulang — lalu tempuh jalannya: fana' dulu, dan biarkan Yang Berbicara berbicara sendiri, atau tidak sama sekali.",
    },
    seharihari: "Seruling berbunyi merdu lalu 'berkata': akulah lagunya. Padahal yang meniup bukan dia — dia cuma bambu berlubang; justru karena kosonglah ia bisa ditiup. Kalau bambu itu lalu sibuk mengaku-aku, peniup berhenti meniup — tinggal bambu bisu. Pelajarannya bukan 'ayo ikut mengaku', tapi 'ayo ikut mengosongkan diri'. Bunyi itu urusan Sang Peniup; kosong itu urusanmu.",
    rujukan: ["QS Thaha 14 (kisah Musa di Thursina)", "Al-Hallaj, Kitab ath-Thawasin", "Rumi, Matsnawi (pembelaan atas Hallaj)", "Al-Junayd tentang sahw & sukr"],
    peringatan: "Kalimat puncak bukan mainan lisan. Ia lahir dari keadaan, bukan dari hafalan; mengulanginya tanpa keadaannya sama seperti memakai seragam dokter lalu membedah orang.",
  },
  {
    id: "insan-kamil",
    istilah: "Insan Kamil",
    asal: "al-insan al-kamil — الإنسان الكامل (manusia paripurna)",
    kategori: "puncak",
    alias: ["manusia sempurna", "manusia paripurna", "al jili", "adam makna", "cermin tuhan", "khalifah"],
    kunci: ["sempurna", "cermin", "khalifah", "mikrokosmos", "jagad cilik"],
    ringkas: "Manusia paripurna: cermin paling bening tempat seluruh Nama-Nya tampil utuh — dan cetak birunya ada di setiap orang.",
    tingkat: {
      syariat: "Allah mengajarkan Adam seluruh nama (QS 2:31) dan menjadikannya khalifah di bumi (QS 2:30); Muhammad ﷺ disebut uswah hasanah — teladan terbaik. Secara lahir, insan kamil adalah akhlak beliau: jujur, kasih, adil, sabar — 'akhlaknya adalah Al-Qur'an' kata 'Aisyah. Jalan menuju paripurna dimulai dari meniru yang paling paripurna.",
      tarekat: "Manusia adalah jagad cilik (mikrokosmos): seluruh unsur jagad gedhe — tanah, air, api, udara; malaikat sampai binatang — terangkum di dalamnya. Laku suluk adalah merapikan seluruh isi jagad kecil itu: unsur binatangnya dijinakkan, unsur malaikatnya ditumbuhkan, sampai seluruh penghuninya sujud kepada Yang Satu — sebagaimana alam raya sujud.",
      hakikat: "Al-Jili merumuskan: insan kamil adalah cermin tempat Allah memandang Diri-Nya secara paripurna. Segala makhluk memantulkan Nama-Nya sekeping-sekeping — langit memantulkan Keagungan, bunga memantulkan Keindahan, ibu memantulkan Kasih — hanya manusia diberi kapasitas memantulkan seluruh Nama dalam satu wajah. Karena itulah malaikat diperintah sujud kepada Adam: bukan menyembah tanahnya, tapi menghormati kapasitas cerminnya.",
      makrifat: "Inti dari intinya: insan kamil bukan manusia yang menjadi hebat, melainkan manusia yang selesai menghalangi. Cermin tidak menambahkan apa-apa pada cahaya — ia hanya berhenti kotor. Nur Muhammad adalah cetak biru itu; para nabi dan wali adalah cermin-cermin yang sudah tergosok; dan kau adalah cermin yang sama dalam keadaan masih berdebu. Maka kabar paling agung sekaligus paling menuntut: kesempurnaan itu bukan untuk dikagumi dari jauh — ia amanahmu yang belum ditunaikan.",
    },
    seharihari: "Semua orang membawa cermin yang sama persis sejak lahir. Bedanya cuma satu: punya siapa yang masih berdebu, punya siapa yang sudah dilap. Nabi dan para wali bukan makhluk jenis lain — mereka manusia yang cerminnya tuntas dibersihkan, supaya kita percaya bahwa cermin kita pun bisa. Maka berhenti berkata 'aku cuma manusia biasa' untuk membenarkan malas: justru karena kau manusia, tuntutanmu paling tinggi se-jagad.",
    rujukan: ["QS al-Baqarah 30–34; al-Ahzab 21", "Abdul Karim al-Jili, al-Insan al-Kamil", "Ibn 'Arabi, Fushush al-Hikam — Fash Adam"],
  },
  {
    id: "nur-muhammad",
    istilah: "Nur Muhammad",
    asal: "an-nur al-muhammadi — النور المحمدي",
    kategori: "puncak",
    alias: ["nur muhammad", "cahaya muhammad", "hakikat muhammadiyah", "haqiqah muhammadiyah", "johar awal", "ruh idhafi"],
    kunci: ["cahaya pertama", "awal penciptaan", "kanjeng nabi", "johar"],
    ringkas: "Cahaya pertama yang dari-Nya segala diadakan — pena pertama yang menulis seluruh kisah.",
    tingkat: {
      syariat: "Secara lahir, Muhammad ﷺ adalah manusia utusan: 'Katakanlah: aku hanyalah manusia seperti kalian yang diberi wahyu' (QS 18:110). Kecintaan kepada beliau diwujudkan dengan shalawat, meneladani sunnah, dan akhlak — bukan dengan mengangkatnya menjadi sesembahan; beliau sendiri melarang dipuja berlebihan seperti Nasrani memuja Isa.",
      tarekat: "Dalam khazanah tarekat dan suluk Jawa (johar awal, ruh idhafi), Nur Muhammad adalah ciptaan pertama: dari cahaya itulah kalam, arasy, dan segala wujud diurai — sebagaimana riwayat yang masyhur di kalangan sufi. Salik menghubungkan diri lewat shalawat: bukan sekadar mendoakan Nabi, melainkan menyambungkan tetes dirinya ke sumber cahayanya.",
      hakikat: "Hakikat Muhammadiyah adalah wajah Allah yang menghadap kepada penciptaan — sisi Kasih yang dengannya segala diadakan: 'Tidaklah Kuutus engkau kecuali sebagai rahmat bagi semesta' (QS 21:107). Muhammad bin Abdillah yang lahir di Makkah adalah penampakan paripurna dari hakikat itu dalam sejarah; hakikatnya sendiri mengatasi ruang-waktu — awwalu ma khalaqallah, yang paling awal.",
      makrifat: "Inti dari intinya: Nur Muhammad adalah jawaban atas pertanyaan 'lewat pintu apa Yang Tak Terhampiri bisa dikenali?' Dzat mutlak tak tersentuh pengenalan; maka Ia menampilkan Diri lewat satu cermin agung yang memuat seluruh Nama — itulah hakikat Muhammadiyah, dan setiap ruh manusia adalah percikannya. Maka mencintai Nabi bukan urusan sentimental: ia jalan pulang lewat garis keturunan cahayamu sendiri. Shalawat adalah arus balik percikan menuju samudra asalnya.",
    },
    seharihari: "Matahari tak bisa kau tatap langsung — matamu terbakar. Tapi bulan bisa kau pandangi semalaman: cahayanya cahaya matahari juga, hanya sudah dilembutkan. Nur Muhammad itu bulannya: Kasih Tuhan yang sudah diturunkan kadarnya supaya bisa didekati, ditiru, dicintai. Bershalawat itu seperti menghadapkan wajah ke bulan — pelan-pelan wajahmu ikut terang, oleh cahaya yang sumbernya sama.",
    rujukan: ["QS al-Kahfi 110; al-Anbiya 107", "Riwayat awwalu ma khalaqallah nuri (masyhur di kalangan sufi)", "Serat Wirid Hidayat Jati (ruh idhafi)", "Qashidah Burdah, al-Bushiri"],
  },
  {
    id: "tajalli",
    istilah: "Tajalli — Takhalli — Tahalli",
    asal: "tajalli — تجلّي (penampakan Ilahi)",
    kategori: "puncak",
    alias: ["tajali", "penampakan", "takhalli", "tahalli", "manifestasi", "pancaran", "penyingkapan tuhan"],
    kunci: ["menampakkan", "kosongkan", "hiasi", "tiga langkah", "gunung musa"],
    ringkas: "Tiga ayunan satu gerak: kosongkan (takhalli), hiasi (tahalli), dan Dia menampakkan Diri (tajalli).",
    tingkat: {
      syariat: "Urutannya akhlak sebelum mistik: takhalli — mengosongkan diri dari sifat tercela (dengki, kikir, dusta, riya); tahalli — mengisinya dengan sifat terpuji (jujur, kasih, sabar, syukur). Dua langkah ini murni kerja keras yang bisa dimulai siapa pun hari ini, tanpa menunggu pengalaman ruhani apa pun.",
      tarekat: "Salik tidak bisa memaksa tajalli datang — ia hanya bisa berbenah. Seperti Musa di gunung: ia hanya bisa mendaki dan memohon; ketika Tuhannya ber-tajalli kepada gunung, hancur luluh gunung itu dan Musa jatuh pingsan (QS 7:143). Pelajarannya dipahat para sufi: wadah harus disiapkan justru karena yang akan datang tak tertanggungkan oleh wadah yang rapuh.",
      hakikat: "Tajalli tidak pernah berhenti — inilah rahasianya. Alam bukan diciptakan sekali lalu ditinggal; ia adalah penampakan-Nya yang diperbarui setiap kejap, dan la takrar fit-tajalli: tak pernah Dia menampak dengan rupa yang sama dua kali. Maka tak ada pagi yang sama, tak ada wajah yang sama, tak ada detik yang sama — yang menganggapnya sama hanyalah pikiran yang malas memandang.",
      makrifat: "Inti dari intinya: yang menghalangi tajalli bukan Dia menahan Diri — Ia azh-Zhahir, Maha Menampakkan — melainkan wadahmu yang penuh. Takhalli dan tahalli sesungguhnya satu pekerjaan: mengosongkan gelas dari isi lama; dan tajalli bukan hadiah yang dikirim dari jauh melainkan kenyataan yang selama ini menunggu gelasmu kosong. Pada arif paripurna, seluruh alam menjadi tajalli yang terbaca: ia melihat Yang Esa menampak di wajah pasar, hujan, musuh, dan cermin kamarnya — dan tak satu pun disembahnya, sebab ia kenal Pemilik semua wajah itu.",
    },
    seharihari: "Rumahmu berantakan, lalu kau mengeluh tamu agung tak pernah datang. Urutannya jelas: buang dulu sampahnya (takhalli), tata dan harumkan ruangannya (tahalli) — soal kapan tamu datang, itu bukan wewenangmu (tajalli). Tapi para tuan rumah yang tekun bersaksi: Tamu itu ternyata tidak pernah tidak datang; selama ini Ia berdiri di depan pintu yang terganjal tumpukan barangmu sendiri.",
    rujukan: ["QS al-A'raf 143; QS al-Hadid 3", "Ibn 'Arabi tentang tajdid al-khalq (penciptaan yang diperbarui)", "Amalan takhalli-tahalli-tajalli dalam kitab-kitab akhlak tasawuf"],
  },
  {
    id: "aku-sejati",
    istilah: "Aku Sejati — Ingsun",
    asal: "Jawa: Ingsun Sejati, pancer",
    kategori: "jawa",
    alias: ["ingsun", "aku sejati", "pancer", "sedulur papat", "limo pancer", "sedulur papat limo pancer", "diri sejati", "sang aku"],
    kunci: ["diri", "saksi", "pusat", "empat saudara", "siapa aku"],
    ringkas: "Empat saudara mengawal satu pusat. Yang kau cari dengan bertanya 'siapa aku' adalah yang sedang bertanya.",
    tingkat: {
      syariat: "Manusia diciptakan dari jasad dan ditiupi ruh dari-Nya (QS 32:9). Jasad, akal, dan perasaan adalah amanah yang dirawat: badan dijaga kesehatannya, akal dijaga kejernihannya, hati dijaga kebersihannya. Mengenali diri dimulai dari mensyukuri perangkat-perangkat ini tanpa menuhankan satu pun darinya.",
      tarekat: "Kejawen memetakan pengawal diri sebagai sedulur papat limo pancer — empat saudara dan yang kelima pusat: empat nafsu (aluamah, amarah, supiyah, mutmainah) yang lahir menyertai setiap bayi, mengawal pancer — sang pusat. Lakunya: mengenali keempat saudara itu, menyapa dan menjinakkannya, bukan memusuhinya; sebab pengawal yang dimusuhi berubah jadi perampok, pengawal yang dididik menjadi tentara.",
      hakikat: "Aku Sejati bukanlah badan (ia berubah dan hancur), bukan pikiran (ia datang-pergi), bukan perasaan (ia pasang-surut), bukan nama dan peran (semua pemberian). Semua itu bisa kau saksikan — maka semua itu bukan penyaksinya. Ingsun adalah saksi yang tak ikut arus: yang sejak kecil hingga tua merasa 'aku tetap aku' meski seluruh sel badan dan seluruh isi kepala sudah berganti total. Ia tak pernah tua, sebab ia tak di dalam waktu.",
      makrifat: "Inti dari intinya: kejar 'aku' itu sampai habis — siapa yang menyaksikan pikiranku? lalu: siapa yang menyaksikan si penyaksi? Pengejaran itu berakhir bukan dengan menemukan sebuah 'aku' terdalam yang bisa digenggam, melainkan dengan tembusnya kenyataan bahwa di ujung sana tidak ada milikmu sama sekali — ruh itu 'dari-Nya' (min ruhihi), pinjaman yang tak pernah putus dari Sang Pemilik. Aku sejati ternyata bukan aku; ia jendela — dan yang memandang lewat jendela itu sejak awal adalah Dia. Di sinilah man 'arafa nafsahu menemukan ujungnya: mengenal diri tuntas berarti menemukan bahwa diri itu tembus pandang.",
    },
    seharihari: "Sejak umur lima tahun sampai tua nanti, badanmu ganti total, pendapatmu berubah semua, perasaanmu bolak-balik ribuan kali — tapi ada satu rasa yang tak pernah berubah: rasa 'aku'. Yang mana dia? Bukan fotomu, bukan KTP-mu, bukan isi kepalamu. Dia yang diam-diam menonton semua itu berganti-ganti. Kenalan dulu dengan penonton itu — sebab selama ini kau sibuk mengurus panggung, dan tak pernah sekali pun menoleh ke bangku penonton.",
    rujukan: ["QS as-Sajdah 9; QS Shad 72", "Suluk Linglung; Serat Wirid Hidayat Jati", "Konsep sedulur papat limo pancer (tradisi lisan & serat kejawen)"],
  },
  {
    id: "sangkan-paran",
    istilah: "Sangkan Paraning Dumadi",
    asal: "Jawa: asal dan tujuan segala kejadian",
    kategori: "jawa",
    alias: ["sangkan paran", "asal usul", "inna lillahi", "dari mana ke mana", "mulih", "pulang", "asal dan kembali"],
    kunci: ["asal", "tujuan", "pulang", "kembali", "perjalanan hidup"],
    ringkas: "Dua pertanyaan yang menyalakan seluruh laku: dari mana aku datang, dan ke mana aku pulang.",
    tingkat: {
      syariat: "Rumusnya diucapkan setiap ada kematian: inna lillahi wa inna ilaihi raji'un — sesungguhnya kita milik Allah dan kepada-Nya kita kembali (QS 2:156). Lahirnya: sadar hidup sementara, maka menyiapkan bekal — iman dan amal — untuk perjalanan pulang yang pasti datang jadwalnya.",
      tarekat: "Bagi salik, kalimat itu bukan ucapan belasungkawa melainkan kompas harian: setiap keputusan diuji dengan 'mendekatkan ke arah pulang atau menjauhkan?' Hidup dipandang sebagai mampir ngombe — singgah minum: yang mampir boleh menikmati warungnya, tapi celaka kalau lupa arah rumahnya dan mengira warung itu rumah.",
      hakikat: "Sangkan (asal) dan paran (tujuan) ternyata satu titik: kau datang dari-Nya dan pulang kepada-Nya, maka hidup bukanlah garis lurus dari A ke B melainkan lingkaran yang menutup. Dan yang ditempuh sesungguhnya bukan jarak — Dia tak pernah jauh — melainkan lupa: turun ke dunia adalah lupa asal, dan seluruh laku ruhani hanyalah bangunnya ingatan. Dzikir artinya persis itu: ingat.",
      makrifat: "Inti dari intinya: milik-Nya (lillahi) bukan kelak saat mati — sekarang pun kau sepenuhnya milik-Nya, dan kembali (raji'un) bukan menunggu jasad dikubur: setiap kejap segala wujud kembali kepada-Nya dan dipancarkan lagi. Yang mengerti ini berhenti menunda: pulang tidak perlu menunggu mati, sebab yang menghalangi bukan jarak melainkan klaim 'aku milik diriku sendiri'. Serahkan klaim itu hari ini, maka hari ini pula sampai. Mulih mula mulanira — pulang ke asal mula — dan asal itu tak pernah sejengkal pun meninggalkanmu.",
    },
    seharihari: "Orang merantau puluhan tahun bisa lupa kampungnya — sibuk, sukses, tenggelam. Lalu suatu malam mencium bau hujan di tanah, dan mendadak rindu rumah sampai sesak. Semua manusia sedang merantau; rasa hampa yang aneh di tengah pesta, rindu tanpa objek yang muncul malam-malam — itu bau hujan tanah kampungmu. Jangan diobati dengan menambah pesta. Itu bukan penyakit; itu kompas yang masih hidup.",
    rujukan: ["QS al-Baqarah 156", "Falsafah urip mung mampir ngombe", "Serat Wedhatama; Serat Centhini"],
  },
  {
    id: "sidratul-muntaha",
    istilah: "Sidratul Muntaha & Mi'raj Batin",
    asal: "sidrat al-muntaha — سدرة المنتهى (pohon batas penghabisan)",
    kategori: "puncak",
    alias: ["sidrah", "miraj", "mi'raj", "isra miraj", "buraq", "buroq", "jibril berhenti", "pohon batas", "perjalanan malam"],
    kunci: ["batas", "puncak", "perjalanan", "naik", "dua busur", "qaba qausain"],
    ringkas: "Batas penghabisan segala makhluk — tempat Jibril pun berkata: selangkah lagi, aku terbakar.",
    tingkat: {
      syariat: "Peristiwanya diimani sebagaimana diberitakan: Nabi ﷺ diperjalankan malam hari dari Masjidil Haram ke Masjidil Aqsha (QS 17:1), lalu dinaikkan melintasi langit hingga Sidratul Muntaha (QS 53:13–18), menerima perintah shalat, dan kembali sebelum fajar. Buah lahirnya jelas dan dibawa pulang untuk semua orang: shalat lima waktu.",
      tarekat: "Bagi salik, mi'raj adalah peta perjalanan batin dan shalat adalah kendaraannya — ash-shalatu mi'rajul mu'min, shalat adalah mi'rajnya orang beriman. Buraq melambangkan himmah — tenaga rindu yang melesat; Jibril melambangkan ilmu dan pembimbing; langit-langit yang dilintasi adalah lapisan-lapisan nafs yang ditembus satu per satu. Setiap takbir adalah isra kecil bagi yang menegakkannya dengan hadir.",
      hakikat: "Di Sidratul Muntaha, Jibril berhenti: 'Seandainya aku maju sejengkal lagi, niscaya aku terbakar.' Inilah hakikat batas: ilmu, guru, kitab, malaikat — semua perantara berhenti di tepi. Langkah melampauinya ditempuh sendirian, tanpa bekal apa pun kecuali dipanggil. Maka dhana fatadalla — Dia mendekat, lalu bertambah dekat, hingga jarak dua ujung busur atau lebih dekat (QS 53:8–9): pada puncak itu bukan hamba yang berhasil naik, melainkan Dia yang menarik.",
      makrifat: "Inti dari intinya: mata beliau tidak berpaling dan tidak melampaui batas (QS 53:17) — di puncak segala puncak, Nabi tetap 'abduhu: hamba-Nya ('Maha Suci Yang memperjalankan hamba-Nya…'). Inilah rahasia yang membedakan mi'raj sejati dari khayalan ketinggian: makin tinggi naik, makin dalam sujudnya. Dan sesudah puncak, beliau pulang — membawa oleh-oleh untuk umat, memimpin pasar dan menahan luka. Perjalanan tertinggi tidak berakhir di langit; ia berakhir di kesediaan turun kembali. Yang menetap mabuk di ketinggian belum selesai; yang sudah selesai justru kembali menyapa tetangganya dengan wajah biasa.",
    },
    seharihari: "Pemandu gunung terbaik pun berhenti di batas tertentu: 'Dari sini, jalurmu sendirian.' Bukan karena pemandu jahat — karena memang begitu aturan puncak itu. Semua guru, buku, dan aplikasi ini adalah pemandu yang tahu diri: mengantar sejauh-jauhnya lalu diam di tepi. Dan tanda orang yang benar-benar pernah sampai puncak bukan cerita hebatnya — tapi ia turun lagi, membawa air untuk yang di bawah, dan tak sombong sedikit pun.",
    rujukan: ["QS al-Isra 1; QS an-Najm 1–18", "Hadits-hadits Isra Mi'raj (Bukhari & Muslim)", "Ungkapan ash-shalatu mi'rajul mu'min (masyhur di kalangan sufi)"],
  },
  {
    id: "tajrid",
    istilah: "Tajrid — Lepas dari Segala Belenggu",
    asal: "tajrid — تجريد (penanggalan); tarku al-'adyan dalam syair sufi",
    kategori: "puncak",
    alias: ["lepas belenggu", "bebas", "murtad", "meninggalkan agama", "tarku adyan", "agama cinta", "melampaui agama", "tanpa topeng", "kemerdekaan"],
    kunci: ["belenggu", "bebas", "lepas", "merdeka", "melampaui", "bentuk"],
    ringkas: "Yang ditanggalkan para arif bukan ibadahnya — melainkan 'agama' yang telah menjadi milik ego: topeng, panggung, dan belenggunya.",
    tingkat: {
      syariat: "Duduk perkaranya perlu jernih sejak awal: tak ada satu pun arif besar yang ajarannya sampai kepada kita — Junayd, Ghazali, Rumi, Ibn 'Arabi, Abdul Qadir al-Jailani — yang meninggalkan syariat. Junayd menegaskan: 'Madzhab kami terikat oleh Al-Qur'an dan Sunnah; siapa tidak hafal Kitab dan tidak menulis hadits, tidak layak diikuti dalam urusan ini.' Justru makin tinggi mereka, makin rapi shalatnya.",
      tarekat: "Yang benar-benar ditanggalkan di jalan ini adalah kelekatan: pada dunia, pada pujian, pada pengalaman ruhani, pada kedudukan suci — dan yang paling licin: kelekatan pada keberagamaan sebagai identitas ego. Ada orang yang agamanya adalah panggung kesombongannya: merasa paling benar, gemar mengkafirkan, ibadahnya untuk ditonton. 'Agama' semacam itulah belenggu yang wajib dilepas — bukan karena agama salah, tapi karena yang dipeluknya bukan agama melainkan egonya yang berjubah.",
      hakikat: "Di sinilah syair-syair yang mengguncang itu berdiri. Rumi: 'Bukan Kristen, Yahudi, atau Muslim aku… tempatku tanpa tempat.' Ibn 'Arabi: 'Hatiku sanggup menerima segala rupa… aku beragama cinta, ke mana pun kafilahnya menghadap.' Mereka tidak sedang keluar dari agama — mereka bersaksi telah menembus dari bentuk ke Pemilik bentuk: sesudah berjumpa Yang Dituju, semua penunjuk arah terlihat sebagai penunjuk arah, dan cinta tak lagi bisa dipenjara oleh sekat golongan. Yang gugur bukan agamanya, melainkan fanatisme kepemilikannya: agama berhenti menjadi 'milikku yang mengalahkan milikmu' dan kembali menjadi jalan pulang.",
      makrifat: "Inti dari intinya — dan di sini banyak yang tergelincir: ada dua cara berhenti terbelenggu perahu. Pertama, membakar perahu di tengah laut — itu bukan kebebasan, itu tenggelam; ego yang bosan aturan sering menyamar sebagai 'sudah sampai'. Kedua, sampai ke seberang — dan lihatlah yang terjadi pada para penyeberang sejati: mereka tidak membakar perahunya; mereka justru merawatnya dan menyeberangkan orang lain dengannya. Ujiannya satu dan tak bisa ditawar: lepasnya belenggu sejati berbuah makin rendah hati, makin kasih, makin ringan melayani — sebab yang lepas adalah ego. Bila 'kebebasanku' berbuah merasa lebih tinggi dari yang masih bersyariat, maka yang terjadi bukan lepasnya belenggu melainkan ganti belenggu: dari belenggu bentuk ke belenggu paling berat — ego yang merasa sudah bebas.",
    },
    seharihari: "Sarung tangan bagi tukang las bisa terasa mengekang — sampai percikan api datang. Orang yang sudah mahir kadang berkata 'aku tak lagi memikirkan sarung tanganku' — maksudnya ia sudah menyatu dengan kerjanya, bukan ia mengelas telanjang tangan. Begitulah kalimat para arif tentang 'melampaui agama': ucapan orang yang tenggelam dalam Kekasih hingga tak lagi menghitung-hitung aturannya — bukan ajakan membuang aturan. Bedanya gampang dites di dapur kehidupan: yang benar-benar bebas itu makin sabar sama tetangga, makin jujur di timbangan, makin ringan menolong. Kalau 'bebas'-nya cuma bikin sombong dan malas — itu bukan sampai ke seberang; itu nyemplung.",
    rujukan: ["Al-Junayd tentang keterikatan pada Al-Qur'an & Sunnah", "Ibn 'Arabi, Tarjuman al-Asywaq", "Rumi, Diwan-e Syams", "Al-Hikam Ibn 'Atha'illah tentang tajrid & asbab"],
    peringatan: "Maqam ini paling sering dipalsukan — oleh ego sendiri. Penanda palsunya: ingin diumumkan, merasa di atas orang beramal, dan berbuah malas serta kasar. Penanda asalnya: sunyi, rendah hati, dan berbuah kasih yang makin luas.",
  },
];

// Teks-teks antarmuka yang bernuansa — dipisah agar mudah diubah.
const TEKS = {
  gerbang: {
    salam: "Sugeng rawuh ing Kandang Ndalem.",
    pambuka: "Ruang ini sunyi dan tertutup: seluruh isinya tinggal di perangkatmu, tak ada yang dikirim ke mana pun. Sebelum masuk, tradisi para pencari selalu mengetuk dengan satu pertanyaan. Jawabanmu tidak dinilai dan tidak disimpan siapa-siapa — ia hanya untuk menghadapkan wajahmu ke dalam.",
    pitakon: "Sapa aku iki? — Siapakah aku ini?",
    tombol: "Singkap Hijab",
    catatan: "Tulis apa saja yang jujur malam ini. Jawaban itu akan berubah seiring jalanmu — dan memang harus berubah.",
  },
  selami: {
    ajakan: "Selami satu kata — makrifat, fana, suwung… — atau satu penunjuk jalan: rumi, kalijaga, ali, gautama…",
    kosong: "Belum ada yang cocok. Coba kata lain, atau buka Peta Suluk untuk melihat seluruh khazanah.",
    sambutan: "Bismillah. Ketik satu istilah atau nama seorang penunjuk jalan, dan ia akan dibedah empat lapis — dari kulit sampai sumsum — lalu dipulangkan ke bahasa sehari-hari. Ketik /godmode bila ingin seluruh lapisan tersingkap sekaligus.",
  },
  godmodeAktif: "Mode Paripurna tersingkap: seluruh lapisan dibuka sekaligus, dari syariat sampai inti dari inti.",
  godmodeMati: "Mode Paripurna ditutup kembali. Lapisan dibuka satu demi satu — sebagaimana adab membuka tirai.",
  jibril: "Sampai di sini kendaraan dan penunjuk jalan berhenti, sebagaimana Jibril berhenti di Sidrah: “Selangkah lagi aku maju, aku terbakar.” Selebihnya bukan wilayah kata-kata. Selebihnya: laku, sunyi, dan Dia.",
};
