// ============================================================
// KANDANG NDALEM — SAYAP PARA PENUNJUK JALAN
// Tokoh-tokoh besar dan kitab-kitabnya, dibedah empat lapis.
// Berkas ini menambah isi DATA dari data.js — dimuat sesudahnya.
// ============================================================

KATEGORI.nabi = "Kafilah Para Nabi";
KATEGORI.sahabat = "Pintu Para Sahabat";
KATEGORI.arif = "Para Arif & Kitab-kitabnya";
KATEGORI.timur = "Cahaya dari Timur";
KATEGORI.filsafat = "Para Pencinta Kebijaksanaan";

const TOKOH = [
  // ---------------------------------------------------------- NABI
  {
    id: "ibrahim",
    istilah: "Ibrahim — Bapak Para Pencari",
    asal: "Khalilullah — kekasih Allah; ibrani: Abraham",
    kategori: "nabi",
    alias: ["ibrohim", "nabi ibrahim", "abraham", "khalilullah", "bapak tauhid", "millah ibrahim", "hanif"],
    kunci: ["berhala", "api", "kurban", "ismail", "pencari", "bintang bulan matahari"],
    ringkas: "Pemuda yang menguji semua cahaya sampai menemukan Sumber cahaya — lalu dites: sanggupkah menyembelih yang paling dicintai?",
    tingkat: {
      syariat: "Bapak tiga agama besar; jalannya disebut hanif — lurus, tak menyekutukan. Kisah lahirnya: membesar di rumah pembuat berhala, menghancurkan berhala-berhala, dibakar Namrud dan api dijadikan dingin (QS 21:69), hijrah — 'Sesungguhnya aku pergi menuju Tuhanku; Dia akan menunjukiku' (QS 37:99) — dan puncaknya perintah menyembelih Ismail yang ditebus Allah. Jejak lakunya diabadikan dalam manasik haji.",
      tarekat: "Metodenya adalah metode setiap pencari jujur: eliminasi. Ia pandang bintang — 'inikah Tuhanku?' — bintang tenggelam; bulan — tenggelam; matahari — tenggelam juga. Lalu kalimat kuncinya: la uhibbul afilin — 'aku tidak menyukai yang tenggelam' (QS 6:76–79). Apa pun yang bisa hilang, bukan Dia. Ujilah semua sandaranmu dengan kalimat itu: harta tenggelam, jabatan tenggelam, badan tenggelam — teruskan sampai habis yang bisa tenggelam.",
      hakikat: "Kapak yang dikalungkannya ke berhala terbesar adalah isyarat: berhala terbesar tidak di kuil — ia di dada, bernama 'aku'. Api Namrud dingin bagi yang tauhidnya tuntas: dunia kehilangan daya bakar atas orang yang tidak lagi menggenggamnya. Dan perintah menyembelih Ismail dibaca para arif: yang diminta Allah bukan nyawa anak itu — buktinya ditebus domba — melainkan kelekatan sang bapak pada yang paling dicintainya. Sembelih kelekatannya, dan yang dicintai justru dikembalikan.",
      makrifat: "Inti Ibrahim ada di satu dialog pendek: 'Aslim!' — berserahlah — 'qala aslamtu' — ia menjawab: aku berserah (QS 2:131). Dari kata itulah nama islam sebagai sikap: penyerahan total. Dan lihat betapa Allah memuliakan pencari: Ibrahim yang sudah nabi masih memohon, 'Tuhanku, perlihatkan padaku bagaimana Engkau menghidupkan yang mati… agar hatiku tenteram' (QS 2:260) — iman-kabar tidak memuaskannya; ia minta penyaksian, dan Allah tidak memarahinya — Allah mengabulkannya. Itulah piagam legitimasi bagi setiap perindu makrifat: boleh, bahkan dicintai, meminta lebih dalam dari sekadar percaya.",
    },
    seharihari: "Seperti anak muda yang mewarisi rumah tua lalu memeriksa sendiri fondasinya satu per satu — bukan karena durhaka pada kakeknya, tapi karena ingin rumah itu benar-benar miliknya, bukan sekadar warisan yang ditinggali tanpa dikenali. Semua yang goyang ia ganti; sampai ketemu fondasi yang tak bisa goyang. Keimanan hasil memeriksa sendiri itulah yang tak bisa dirobohkan siapa-siapa.",
    rujukan: ["QS al-An'am 74–79; al-Anbiya 51–70; ash-Shaffat 83–113; al-Baqarah 124–132, 260"],
  },
  {
    id: "musa",
    istilah: "Musa — Kalimullah",
    asal: "Kalimullah — yang diajak bicara Allah",
    kategori: "nabi",
    alias: ["nabi musa", "moses", "kalimullah", "taurat", "thursina", "khidir", "nabi khidir"],
    kunci: ["gunung", "tongkat", "laut", "semak api", "sandal", "ladunni"],
    ringkas: "Nabi yang bicara langsung dengan Allah, meminta melihat-Nya, dan dikirim berguru pada hamba misterius di pertemuan dua lautan.",
    tingkat: {
      syariat: "Pembawa Taurat, syariat yang paling tegas; pembebas Bani Israil dari Fir'aun; laut dibelah untuknya. Kisahnya paling sering diulang Al-Qur'an — sebab perjuangannya paling mirip perjuangan manusia biasa: pernah salah, pernah lari, pernah takut, pernah tak fasih bicara, dan tetap dipilih.",
      tarekat: "Sebelum diangkat, ia digembleng: sepuluh tahun menggembala kambing di Madyan — calon pemimpin umat dilatih lewat pekerjaan paling sunyi. Di Thursina ia diperintah: 'Lepaskan kedua sandalmu' (QS 20:12) — para arif membacanya: tanggalkan dua kelekatan, dunia dan akhirat, bila hendak menginjak lembah suci. Lalu: 'Apa itu di tangan kananmu, Musa?' — tongkat, andalannya — 'Lemparkan!' Yang kau genggam harus berani kau lempar; sesudah dilempar barulah tampak kekuatan sebenarnya yang selama ini tersimpan di dalamnya.",
      hakikat: "Dari semak yang menyala ia mendengar 'Sesungguhnya Akulah Allah' (QS 20:14) — semak tidak menjadi Tuhan; Tuhan bersuara melewati semak (selami: Ana al-Haqq). Dan ketika ia memohon 'Tuhanku, perlihatkan Diri-Mu agar aku memandang-Mu', jawabnya: lan tarani — 'engkau tak akan melihat-Ku' — lalu Dia ber-tajalli ke gunung, gunung luluh, Musa pingsan (QS 7:143). Pelajaran yang dipahat para sufi: bukan Allah pelit dilihat — wadah 'aku' yang belum sanggup; gunung saja hancur, apalagi ego. Yang ingin memandang harus bersedia luluh dulu.",
      makrifat: "Lalu babak paling dalam: Musa — nabi besar pemegang syariat — dikirim berguru kepada hamba di pertemuan dua lautan yang diberi 'ilmu dari sisi Kami' (ladunni): Khidir (QS 18:60–82). Perahu dilubangi, anak dibunuh, dinding ditegakkan — tiga kali Musa protes dengan hukum lahir, dan tiga-tiganya keliru menurut ilmu batin. Tapi perhatikan keseimbangannya: Khidir tidak membatalkan syariat Musa, dan Musa tidak dibuang dari maqamnya — keduanya hamba dengan tugas berbeda. Inilah pertemuan dua lautan yang sesungguhnya: lautan syariat dan lautan hakikat bertemu tanpa saling menenggelamkan. Yang menolak salah satunya, tenggelam di lautan yang ia tolak.",
    },
    seharihari: "Seperti ahli hukum senior yang dikirim magang ke pedalaman pada seorang tua yang tak punya gelar — dan tiga kali dibikin bingung karena keputusan si tua tampak melanggar buku, tapi belakangan terbukti menyelamatkan banyak orang. Buku aturannya tidak salah; matanya saja yang belum melihat data yang dilihat si tua. Maka jangan buang bukumu, dan jangan pula sombong dengan bukumu.",
    rujukan: ["QS Thaha 9–48; al-A'raf 143; al-Kahfi 60–82; al-Qashash 1–35"],
  },
  {
    id: "isa",
    istilah: "Isa — Ruhullah",
    asal: "Kalimatullah wa ruhun minhu — kalimat & ruh dari-Nya",
    kategori: "nabi",
    alias: ["nabi isa", "yesus", "isa al masih", "almasih", "ruhullah", "putra maryam", "injil"],
    kunci: ["maryam", "zuhud", "kerajaan", "cinta", "nafas", "hati"],
    ringkas: "Nabi hati: lahir dari yang suci, hidup tanpa menggenggam dunia, mengajarkan Kerajaan yang ada di dalam.",
    tingkat: {
      syariat: "Dalam Islam: Isa putra Maryam adalah kalimat Allah yang disampaikan kepada Maryam dan ruh dari-Nya (QS 4:171) — hamba dan utusan, bukan tuhan; lahir tanpa ayah sebagaimana Adam tanpa ayah-ibu (QS 3:59); menghidupkan yang mati dan menyembuhkan dengan izin Allah; diangkat, tidak disalib menurut QS 4:157. Saudara-saudara Nasrani memuliakannya lebih dari itu — perbedaan akidah ini nyata dan tidak perlu disamarkan; entri ini membaca inti ajarannya, yang kedua umat sama-sama mewarisinya.",
      tarekat: "Ia teladan zuhud paripurna dalam khazanah sufi: tidur beralas bumi, berbantal batu, tak menyimpan makanan untuk esok. Atsar yang dicintai para arif — sampai dipahatkan di gerbang masjid Fatehpur Sikri: 'Dunia adalah jembatan. Lewatilah, jangan bangun rumah di atasnya.' Dan ajarannya yang paling menggetarkan ego: kasihi musuhmu; diberi tampar pipi kanan, beri pipi kiri — bukan kelemahan, melainkan mogoknya total mesin balas-membalas yang menghidupi ego.",
      hakikat: "'Kerajaan Allah tidak datang dengan tanda-tanda lahiriah… sebab Kerajaan Allah ada di dalam dirimu' (Lukas 17:21) — itulah makrifat berbahasa Injil. Berbahagialah yang miskin di hadapan Allah — itulah faqr para sufi. Dan kelahirannya dari perawan dibaca para arif sebagai lambang yang berlaku bagi setiap salik: hanya hati yang perawan — bersih dari benih selain-Nya — yang bisa melahirkan Kalimah di dalam dirinya.",
      makrifat: "Ia digelari Ruhullah — dan di sinilah rahasianya bagi kita: pada Isa, Allah memperlihatkan secara terang apa yang pada setiap manusia tersimpan redup — bahwa ruh ini dari tiupan-Nya (QS 32:9). Nafasnya menghidupkan burung tanah dengan izin Allah; para arif berkata: itulah daya nafas ar-Rahman yang mengalir bila 'aku' tidak menyumbatnya. Isa akan kembali di akhir zaman, kata riwayat — dan sebagian arif menambahkan: ia juga 'kembali' setiap kali sebuah hati mati dihidupkan oleh kasih. Yang menunggu kedatangannya di langit jangan lupa menyambutnya di dada.",
    },
    seharihari: "Seperti guru yang tidak meninggalkan gedung sekolah, yayasan, atau buku cetak — hanya cara hidup yang begitu bersih sehingga dua ribu tahun kemudian orang masih berdebat memperebutkannya. Ajarannya bisa diringkas satu kalimat yang paling sulit dipraktikkan di dunia: berhenti membalas, mulai mengasihi. Coba sehari saja — kau akan tahu kenapa ia disebut ruh dari-Nya.",
    rujukan: ["QS Ali 'Imran 45–59; an-Nisa 157, 171; Maryam 16–36", "Lukas 17:21; Matius 5 (Khotbah di Bukit)", "Atsar-atsar Isa dalam Ihya' al-Ghazali"],
  },
  {
    id: "muhammad-utusan",
    istilah: "Muhammad ﷺ — Penerima Wahyu",
    asal: "'Abduhu wa Rasuluh — hamba-Nya dan utusan-Nya",
    kategori: "nabi",
    alias: ["muhammad", "nabi muhammad", "rasulullah", "kanjeng nabi", "baiat", "bai'at", "penerima wahyu", "hira", "ummi"],
    kunci: ["wahyu", "gua hira", "iqra", "baiat", "tangan", "bentuk asli"],
    ringkas: "Manusia yang gemetar menerima wahyu pertama — dan rahasia bai'at: tangan di atas tangan, sambungan yang tak pernah putus.",
    tingkat: {
      syariat: "Yatim sejak dalam kandungan, penggembala, pedagang jujur bergelar al-Amin sebelum jadi nabi. Usia 40, di gua Hira, malaikat mendekapnya: 'Iqra!' — 'aku tidak bisa membaca' — tiga kali, sampai turun ayat pertama. Ia pulang gemetar: 'Selimuti aku, selimuti aku.' Perhatikan kejujuran itu: penerima wahyu terbesar tidak mengarang kesan hebat — ia takut, dan diteguhkan Khadijah. 'Katakanlah: aku hanyalah manusia seperti kalian, yang diwahyukan kepadaku' (QS 18:110).",
      tarekat: "Di sinilah rahasia bai'at yang kau tanyakan. Di bawah pohon di Hudaibiyah para sahabat berjabat tangan bersumpah setia, dan turun ayat: 'Sesungguhnya orang-orang yang berbai'at kepadamu, sebenarnya berbai'at kepada Allah — tangan Allah di atas tangan mereka' (QS 48:10). Tangan manusia menggenggam tangan manusia, dan yang bekerja adalah Tangan Allah: itulah sambungan (silsilah) yang oleh tarekat-tarekat dijaga turun-temurun lewat bai'at guru-murid sampai hari ini — bukan upacara kosong, melainkan kabel yang tersambung ke pembangkit lewat rantai yang tak putus.",
      hakikat: "Ummi — tak bisa baca-tulis — bukan kekurangan melainkan syarat kemurnian: lembaran yang belum pernah ditulisi manusia, sehingga yang tertulis padanya murni dari Allah. Seperti seruling: justru karena kosong ia bisa ditiup (selami: Ana al-Haqq). 'Akhlaknya adalah Al-Qur'an,' kata 'Aisyah — wahyu tidak hanya lewat di lidahnya; wahyu menjadi cara berjalannya, cara marahnya, cara memaafkannya. Penerima yang sempurna adalah yang dirinya sendiri menjadi bacaan.",
      makrifat: "Dan inilah dua wajah yang kau tanyakan: Muhammad bin Abdillah dalam sejarah — yang lahir di Makkah, berdagang, berperang, wafat di Madinah — dan bentuk aslinya: Nur Muhammad, hakikat Muhammadiyah, cahaya pertama yang dari-Nya segala diadakan (selami: Nur Muhammad). Keduanya satu, sebagaimana matahari dan terbitnya di suatu pagi. Rahasia penghabisannya termuat dalam syahadat sendiri: 'abduhu wa rasuluh — hamba-Nya dulu, baru utusan-Nya. Kehambaan yang paripurna adalah wadah risalah yang paripurna: makin habis 'aku'-nya, makin utuh cahaya lewat. Di Sidratul Muntaha, pada jarak dua busur, gelarnya tetap: hamba. Itulah bentuk asli yang sesungguhnya — cermin yang begitu bersih hingga yang tampak padanya hanya Wajah Yang Memandang.",
    },
    seharihari: "Dari semua gelas di dunia, yang dipilih untuk menampung tuangan paling murni adalah gelas yang paling kosong dan paling bersih. Dan bukti keasliannya justru kesederhanaannya: sesudah menerima segalanya — langit dibelah untuknya, negara tunduk padanya — beliau tetap menambal sandalnya sendiri, memerah susu kambingnya sendiri, dan wafat berbantal tikar yang membekas di pipinya. Keagungan yang tidak perlu panggung: itulah tanda barang asli.",
    rujukan: ["QS al-'Alaq 1–5; al-Kahfi 110; al-Fath 10, 18; an-Najm 1–18", "Sirah: Ibn Hisyam — permulaan wahyu", "Selami juga: Nur Muhammad, Sidratul Muntaha"],
  },
  {
    id: "kafilah-nabi",
    istilah: "Kafilah Para Nabi — Satu Pesan",
    asal: "al-anbiya' wal-mursalin — para nabi dan utusan",
    kategori: "nabi",
    alias: ["para nabi", "nabi", "rasul", "paranabi", "25 nabi", "adam", "nuh", "yusuf", "ayub", "yunus", "dawud", "sulaiman"],
    kunci: ["utusan", "kafilah", "satu pesan", "estafet", "peta batin"],
    ringkas: "Ribuan utusan, satu kalimat: tiada tuhan selain Aku, maka kembalilah. Kisah mereka bukan sejarah orang lain — ia peta batinmu.",
    tingkat: {
      syariat: "Dua puluh lima disebut Al-Qur'an; riwayat menyebut 124.000 diutus ke segala umat — 'tidak ada satu umat pun kecuali pernah datang padanya pemberi peringatan' (QS 35:24). Pesan intinya satu untuk semua: 'Tidak Kami utus seorang rasul pun sebelummu melainkan Kami wahyukan padanya: tiada tuhan selain Aku, maka sembahlah Aku' (QS 21:25). Dan adab kita: 'kami tidak membeda-bedakan seorang pun di antara rasul-rasul-Nya' (QS 2:285).",
      tarekat: "Setiap nabi adalah satu wajah laku yang bisa kau pakai hari ini. Adam: taubat — 'Tuhan kami, kami menzalimi diri kami sendiri' — jatuh bukan akhir, melainkan awal jalan pulang. Nuh: istiqamah menyeru 950 tahun tanpa hasil kelihatan. Yusuf: menjaga kesucian di puncak godaan, lalu memaafkan total: 'tiada cela atas kalian hari ini.' Ayub: sabar yang tak menggugat. Yunus: dzikir dalam tiga lapis kegelapan — perut ikan, laut, malam: 'la ilaha illa anta, subhanaka, inni kuntu minazh-zhalimin' (QS 21:87). Dawud: tangis dan kembali. Sulaiman: memegang kerajaan terbesar dengan hati yang tidak digenggamnya.",
      hakikat: "Para arif membaca kisah-kisah itu ke dalam: banjir Nuh adalah banjir nafsu yang menenggelamkan siapa pun yang tak naik bahtera (bahtera = tarekat, laku yang menyelamatkan); sumur tempat Yusuf dibuang adalah keterpurukan yang ternyata jalur menuju istana; ikan Yunus adalah kegelapan batin — depresi, kehilangan arah — yang bila diisi dzikir berubah dari kuburan menjadi rahim. Kau tidak sedang membaca sejarah; kau sedang membaca dirimu dengan nama-nama samaran.",
      makrifat: "Inti dari intinya: satu Cahaya berestafet dari pelita ke pelita — beda kaca, beda zaman, beda bahasa, satu Sumber (selami: Nur Muhammad). Karena itu di puncak, 'tidak membeda-bedakan para rasul' bukan basa-basi diplomasi melainkan penglihatan: semua utusan adalah wajah-wajah dari satu Rahmat yang sama, sebagaimana ribuan lampu jalan menyala dari satu jaringan listrik. Dan ketika kenabian ditutup, alirannya tidak berhenti: para pewaris — ulama yang mengamalkan, wali yang menyembunyikan diri — meneruskan tugas kabel tanpa membawa gelar. Pintu wahyu ditutup; pintu cahaya tidak pernah.",
    },
    seharihari: "Dari kampungmu sampai rumahmu, tiang lampu jalan berdiri berjajar — beda bentuk, beda tinggi, ada yang tua ada yang baru, tapi satu jaringan listrik. Orang bodoh berdebat tiang mana yang paling hebat sampai lupa berjalan pulang. Orang berjalan memakai semua cahayanya, berterima kasih pada setiap tiang, dan hatinya pada Pemilik jaringan.",
    rujukan: ["QS al-Anbiya 25, 87; Fathir 24; al-Baqarah 285; Yusuf 92", "Kisah para nabi: QS Hud, Yusuf, al-Anbiya, ash-Shaffat"],
  },

  // ---------------------------------------------------------- SAHABAT
  {
    id: "abu-bakar",
    istilah: "Abu Bakar — Ash-Shiddiq",
    asal: "ash-Shiddiq — yang membenarkan tanpa jeda",
    kategori: "sahabat",
    alias: ["abu bakar", "abubakar", "as siddiq", "ash shiddiq", "khalifah pertama", "sahabat gua"],
    kunci: ["gua", "membenarkan", "sirr", "dada", "harta"],
    ringkas: "Yang membenarkan tanpa menawar — dan di dadanya, kata riwayat, menetap sesuatu yang membuatnya melampaui semua ahli ibadah.",
    tingkat: {
      syariat: "Sahabat terdekat, mertua Nabi, khalifah pertama. Saat orang meragukan kisah Isra, jawabnya menjadi gelarnya: 'Jika ia yang mengatakannya, aku percaya — bahkan yang lebih jauh dari itu pun aku percaya.' Ditanya apa yang ia tinggalkan untuk keluarganya setelah menyerahkan seluruh hartanya: 'Kutinggalkan bagi mereka Allah dan Rasul-Nya.' Wafat sederhana, berwasiat dikafani kain yang sudah dipakainya.",
      tarekat: "Di gua Tsur, saat kaki para pemburu terlihat dari mulut gua, ia gemetar — bukan untuk nyawanya, untuk nyawa Nabi. Turun ayat: 'Jangan bersedih, sesungguhnya Allah bersama kita' (QS 9:40). Tradisi Naqsyabandiyah menyimpan kenangan itu sebagai akar dzikir khafi — dzikir tersembunyi tanpa suara yang diajarkan dalam kesunyian gua; karena itu silsilah mereka disebut shiddiqiyyah, mengalir lewat Abu Bakar. Sunyi, tersembunyi, tanpa panggung: persis wataknya.",
      hakikat: "Atsar yang masyhur di kalangan sufi: 'Abu Bakar tidak melampaui kalian karena banyaknya shalat atau puasa, melainkan karena sesuatu yang menetap di dadanya.' Para arif menunjuk: itulah sirr — rahasia antara hamba dan Tuhannya yang tak berbentuk amal lahir (selami: Lathaif). Dan darinya pula diwariskan kalimat yang menjadi mahkota entri Makrifat: 'Ketaksanggupan menjangkau pengenalan — itulah pengenalan.'",
      makrifat: "Shiddiq artinya: tidak ada jarak antara mendengar kebenaran dan membenarkannya. Ego selalu minta waktu — 'kupikir-pikir dulu' — bukan untuk berpikir, melainkan untuk menawar posisi. Pada Abu Bakar mesin penawar itu sudah wafat lebih dulu dari badannya: cermin tanpa jeda, memantulkan seketika. Itulah kenapa dadanya bisa dititipi yang tak bisa dititipkan pada dada lain — wadah rahasia hanyalah dada yang berhenti berunding dengan kebenaran.",
    },
    seharihari: "Semua orang punya satu ujian yang sama: saat kebenaran datang menagih sesuatu yang mahal — harta, gengsi, rasa aman. Kebanyakan kita menawar dulu: nanti, sebagian, lihat situasi. Abu Bakar adalah manusia yang tombol tawarnya sudah dicopot. Mulailah kecil: sekali saja hari ini, saat tahu sesuatu benar, langsung kerjakan tanpa rapat internal dengan egomu. Itu satu tetes shiddiq.",
    rujukan: ["QS at-Taubah 40", "Riwayat keutamaan Abu Bakar (Bukhari–Muslim)", "Silsilah shiddiqiyyah Naqsyabandiyah"],
  },
  {
    id: "umar",
    istilah: "'Umar ibn al-Khaththab — Al-Faruq",
    asal: "al-Faruq — sang pemisah haq dan batil",
    kategori: "sahabat",
    alias: ["umar", "umar bin khattab", "al faruq", "khalifah kedua", "amirul mukminin"],
    kunci: ["adil", "keras", "muhasabah", "ilham", "pemisah"],
    ringkas: "Dari penentang paling keras menjadi pilar paling kokoh — pemegang dua imperium yang jubahnya bertambal dua belas.",
    tingkat: {
      syariat: "Masuk Islam sesudah menjadi penentang paling ditakuti — jawaban atas doa Nabi. Khalifah kedua: Persia dan Syam takluk di masanya, dan justru di puncak itu ia ronda malam memikul sendiri karung gandum untuk janda yang anaknya menangis lapar. Kalimatnya jadi pedoman: 'Hisablah dirimu sebelum kalian dihisab.'",
      tarekat: "Lakunya wara' dan muhasabah tanpa ampun — kepada dirinya sendiri lebih keras daripada kepada siapa pun: 'Seandainya seekor keledai terperosok di jalan Irak, aku takut Allah menanyaiku: mengapa tidak kau ratakan jalannya, 'Umar?' Kekuasaan sebesar itu dipegang dengan tangan, tidak dimasukkan ke hati — tajrid di tengah takhta, khalwat dar anjuman dalam bentuk paling sulit: menyepi di tengah urusan negara (selami: Khalwat).",
      hakikat: "Nabi bersabda: 'Pada umat-umat sebelum kalian ada orang-orang muhaddatsun — yang diberi ilham tanpa kenabian. Jika ada pada umatku, dialah 'Umar.' Ini kabar besar bagi kelas ini: makrifat bukan monopoli penghuni gua — ia bisa menyala pada kepala negara yang sibuk, asal dadanya bening. Beberapa kali Al-Qur'an turun sejalan dengan pendapatnya (muwafaqat 'Umar): hati yang lurus beresonansi dengan yang di atas langit.",
      makrifat: "Gelarnya membuka intinya: al-Faruq, sang pemisah. Yang lahir memisahkan haq dan batil di medan sejarah; yang batin memisahkannya di dalam dada setiap kejap — dan itulah senjata makrifat yang sesungguhnya: tamyiz, penglihatan yang tak bisa dikelabui kemasan. Ego paling licin sekalipun kalah cepat dari mata yang sudah selesai dengan dirinya sendiri. Ia wafat ditikam saat mengimami shalat Subuh — penguasa separuh dunia pulang dalam keadaan sedang menghadap, di barisan terdepan penghambaan.",
    },
    seharihari: "Bayangkan pejabat yang takut memakai pulpen kantor untuk keperluan pribadi — bukan takut ketahuan wartawan, takut ditanya Tuhan. Kekuasaan tidak otomatis merusak; yang merusak adalah kekuasaan yang masuk ke hati. 'Umar membuktikan keduanya bisa dipisah: dunia digenggam penuh di tangan, hati kosong melompong dari dunia. Ujiannya bukan saat kau lemah — ujiannya saat kau menang.",
    rujukan: ["Riwayat muhaddatsun (Bukhari–Muslim)", "Sirah 'Umar: Ibn Sa'd, Thabaqat", "Atsar: hisablah dirimu sebelum dihisab"],
  },
  {
    id: "utsman",
    istilah: "'Utsman ibn 'Affan — Dzun Nurain",
    asal: "Dzun Nurain — pemilik dua cahaya",
    kategori: "sahabat",
    alias: ["utsman", "usman", "usman bin affan", "dzun nurain", "khalifah ketiga", "mushaf"],
    kunci: ["malu", "haya", "dermawan", "mushaf", "diam"],
    ringkas: "Yang malaikat pun malu kepadanya — saudagar besar yang menyatukan bacaan umat dan memilih diam saat dikepung.",
    tingkat: {
      syariat: "Menikahi dua putri Nabi berturut-turut — karenanya digelari pemilik dua cahaya. Saudagar kaya yang hartanya mengalir: membeli sumur Rumah untuk umum, membiayai pasukan di masa paceklik. Karya terbesarnya administratif: menyatukan penulisan mushaf sehingga umat sedunia hari ini membaca Al-Qur'an yang satu — mushaf 'Utsmani.",
      tarekat: "Maqamnya haya' — malu ruhani. Nabi bersabda: 'Tidakkah aku pantas malu kepada orang yang para malaikat pun malu kepadanya?' Malu di sini bukan minder, melainkan kepekaan yang menghaluskan seluruh gerak: malu kepada Allah melebihi malu kepada manusia, sehingga sendirian pun lakunya tetap terjaga. Hartanya menunjukkan tajrid versi saudagar: kekayaan di tangan yang tidak digenggam hati mengalir deras tanpa diumumkan.",
      hakikat: "Perhatikan rahasia mushaf: pekerjaan yang tampak teknis — menyeragamkan salinan — sesungguhnya menjaga pintu makrifat seluruh generasi sesudahnya; sebab setiap arif di kelas ini menimba dari Kitab yang ia jaga keutuhannya. Amal lahir yang paling administratif bisa menjadi karya batin paling raksasa: jangan remehkan kerja yang sunyi dari sorot.",
      makrifat: "Akhir hidupnya membuka intinya: dikepung pemberontak di rumahnya sendiri, ia melarang para sahabat mengangkat senjata — memilih darahnya sendiri tumpah daripada darah umat. Ia wafat sambil membaca mushaf; riwayat masyhur menyebut darahnya menetes di ayat 'maka Allah akan mencukupkanmu terhadap mereka' (QS 2:137). Diam terakhirnya bukan kekalahan: itu haya' yang paripurna — bahkan membela diri pun ia malu, sebab Pemiliknya menyaksikan, dan bagi yang yakin disaksikan, pembelaan sudah selesai sebelum dimulai.",
    },
    seharihari: "Ada orang kaya yang sedekahnya lebih besar dari gaya hidupnya dan tak pernah masuk unggahan siapa pun. Ada orang difitnah habis-habisan yang memilih tidak membalas — bukan karena kalah bukti, karena selesai kebutuhannya akan pembenaran manusia. Dua-duanya langka; 'Utsman keduanya sekaligus. Ukur dirimu dengan ini: seberapa banyak kebaikanmu yang benar-benar tak diketahui siapa pun?",
    rujukan: ["Riwayat haya' 'Utsman (Muslim)", "Kisah kodifikasi mushaf (Bukhari)", "Sirah pengepungan: Thabari"],
  },
  {
    id: "ali",
    istilah: "'Ali ibn Abi Thalib — Pintu Kota Ilmu",
    asal: "Babul 'ilmi — pintu kota ilmu; karramallahu wajhah",
    kategori: "sahabat",
    alias: ["ali", "sayidina ali", "sayyidina ali", "ali bin abi thalib", "imam ali", "babul ilmi", "nahjul balaghah", "futuwwah"],
    kunci: ["pintu", "ilmu", "silsilah", "kesatria", "tirai", "yakin"],
    ringkas: "'Seandainya tirai disingkap, keyakinanku tidak bertambah' — pintu yang dilalui hampir semua silsilah tarekat.",
    tingkat: {
      syariat: "Dibesarkan di rumah Nabi sejak kecil; pemuda pertama yang beriman; tidur di ranjang Nabi pada malam hijrah — menyerahkan nyawanya sebagai umpan; menantu Nabi, suami Fathimah, ayah Hasan dan Husain; khalifah keempat; syahid ditikam saat menuju shalat Subuh. Kesatriaannya melahirkan seruan futuwwah: la fata illa 'Ali — tiada pemuda sejati selain 'Ali.",
      tarekat: "'Aku kota ilmu dan 'Ali pintunya' — sabda yang dipegang kaum tarekat: hampir semua silsilah mengalir lewat 'Ali (dan jalur Naqsyabandiyah lewat Abu Bakar). Futuwwah-nya menjadi kurikulum: Rumi mengabadikan kisahnya di Matsnawi — musuh yang sudah kalah meludahi wajahnya, dan 'Ali menurunkan pedang, membatalkan bunuhnya: 'Tadi aku berperang karena Allah; setelah kau ludahi, amarahku ikut campur — aku tak mau membunuh karena amarah diriku.' Itulah bedanya laku dan nafsu yang menyamar laku.",
      hakikat: "'Salunni — bertanyalah kepadaku sebelum kalian kehilanganku': keberanian yang hanya mungkin dari dada yang penuh. Khutbah-khutbah tauhidnya terkumpul dalam Nahjul Balaghah. Dan kalimat yang dinisbatkan kepadanya menjadi puncak entri ini: law kusyifal ghitha' ma-zdadtu yaqina — 'seandainya tirai disingkap, keyakinanku tidak bertambah.' Artinya: ia sudah hidup dalam penyaksian; kematian baginya hanya formalitas administrasi (selami: Mati Sajroning Urip).",
      makrifat: "Kepadanya juga dinisbatkan dua kalimat yang menjadi tiang kelas ini: 'siapa mengenal dirinya mengenal Tuhannya' dan 'aku mengenal Tuhanku dengan Tuhanku.' Dan ucapannya sambil menunjuk dadanya: 'Sungguh di sini ilmu bertumpuk-tumpuk, andai kutemukan pemikulnya.' Ia mencari pemikul, bukan penonton — sebab ilmu rahasia bukan barang pamer melainkan beban amanah: salah pikul, patah punggung si pemikul dan tumpah isinya. Pintu kota tidak menahan orang masuk; ia menyaring siapa yang sanggup berjalan di dalam kota tanpa tersesat.",
    },
    seharihari: "Kunci serep sebuah rumah besar tidak diberikan pada sembarang orang — bukan karena pemiliknya pelit, tapi karena isi rumah bisa mencelakakan yang tak tahu letak-letaknya. 'Ali adalah pemegang kunci yang seumur hidup mencari orang yang layak dititipi — dan lebih sering pulang dengan kunci masih di sakunya. Kalau kau merasa 'ilmu rahasia' mudah didapat dari video singkat, itu bukan isi rumah; itu brosurnya.",
    rujukan: ["Nahjul Balaghah", "Matsnawi Rumi, buku I (kisah 'Ali dan ludah)", "Riwayat babul 'ilmi (Tirmidzi, al-Hakim — diperbincangkan derajatnya, dicintai maknanya)"],
  },
  {
    id: "aisyah",
    istilah: "'Aisyah — Kesaksian dari Dalam Rumah",
    asal: "Ummul Mukminin, al-Humaira",
    kategori: "sahabat",
    alias: ["aisyah", "siti aisyah", "ummul mukminin", "humaira", "istri nabi"],
    kunci: ["rumah", "cinta", "ilmu", "akhlak", "saksi"],
    ringkas: "Yang paling tahu rahasia Sang Cermin adalah yang melihatnya saat tak dilihat siapa-siapa: di rumah.",
    tingkat: {
      syariat: "Putri Abu Bakar, istri tercinta Nabi, Ibunda kaum beriman. Salah satu periwayat hadits terbanyak; para sahabat senior datang bertanya kepadanya tentang hukum waris dan fiqh yang rumit. Sesudah Nabi wafat, hampir setengah abad ia menjadi guru umat — madrasah berjalan dari balik tirai kamarnya.",
      tarekat: "Ilmunya lahir dari cinta yang dekat dan pertanyaan yang berani — ia tak pernah malu bertanya sampai tuntas, dan lewat pertanyaannya umat mewarisi jawaban-jawaban yang tak akan pernah ada. Dialah saksi laku malam Nabi: kaki beliau bengkak karena panjangnya berdiri shalat, dan ketika ditanya mengapa masih begitu padahal telah diampuni, jawab beliau lewat riwayatnya sampai ke kita: 'Tidakkah pantas aku menjadi hamba yang bersyukur?' Ibadah bukan transaksi tebusan — ia luapan syukur.",
      hakikat: "Ketika orang bertanya seperti apa akhlak Nabi, jawaban terdalam keluar dari kamarnya, bukan dari mimbar: 'Akhlaknya adalah Al-Qur'an.' Renungkan kedudukan kesaksian ini: hakikat kenabian dilaporkan oleh yang melihatnya di dapur, saat lelah, saat bercanda, saat ekonomi rumah kosong berbulan-bulan — dan kesaksiannya: sama bersihnya dengan di mimbar. Kedalaman sejati diuji pada versi rumahnya, bukan versi panggungnya.",
      makrifat: "'Aisyah membuktikan satu rahasia yang membebaskan: makrifat tidak mensyaratkan gua. Kamar rumah tangga — dengan cemburu, kekurangan, fitnah yang pernah menimpanya dan dijawab langit sendiri (QS 24) — menjadi madrasah kedalaman. Cinta yang sehari-hari, bila jujur, adalah tarekat juga: yang mencintai paling dekat, mengenal paling dalam; dan yang mengenal paling dalam pada yang paling dicintai Allah, ikut tersambung pada Yang Mencintainya. Separuh khazanah agama ini mengalir lewat perempuan — jangan biarkan siapa pun mengecilkan itu.",
    },
    seharihari: "Orang hebat mudah dinilai dari panggungnya; pasangannya yang tahu aslinya. Kalau kesaksian dari dalam rumah berkata 'ia sama di dalam dan di luar' — itu kesaksian tertinggi yang bisa diterima manusia. Maka ukur kedalaman ruhanimu bukan dari kesan jamaah, tapi dari kesaksian orang serumahmu: mereka dewan penguji yang tak bisa disuap.",
    rujukan: ["QS an-Nur 11–26", "Riwayat 'akhlaknya Al-Qur'an' (Muslim)", "Riwayat kaki bengkak & hamba bersyukur (Bukhari–Muslim)"],
  },
  {
    id: "salman",
    istilah: "Salman al-Farisi — Sang Pencari",
    asal: "Salman al-Farisi — Salman dari Persia",
    kategori: "sahabat",
    alias: ["salman", "salman al farizi", "salman alfarisi", "salman dari persia", "pencari kebenaran"],
    kunci: ["pencarian", "pindah agama", "majusi", "pendeta", "keluarga", "parit"],
    ringkas: "Melintasi agama demi setia pada kebenaran — dan berujung bukan mengambang, melainkan pulang: 'Salman bagian dari keluarga kami.'",
    tingkat: {
      syariat: "Anak bangsawan Persia, penjaga api Majusi. Melihat cara sembahyang orang Nasrani, hatinya tergetar — ia tinggalkan istana ayahnya, berguru dari gereja ke gereja di Syam; setiap gurunya wafat, ia minta ditunjukkan orang terbaik berikutnya. Guru terakhir berwasiat: zaman nabi akhir sudah dekat, negerinya berpohon kurma di antara dua bukit batu hitam. Dalam perjalanan ia dikhianati, dijual jadi budak ke Yatsrib — dan justru di situlah Nabi hijrah. Ia menguji tanda-tanda, beriman, ditebus dari perbudakan.",
      tarekat: "Metode pencariannya adalah adab pencari sejati: berpindah bukan karena bosan melainkan karena mengikuti cahaya; setiap pindah atas petunjuk guru sebelumnya, bukan atas selera sendiri; dan setiap tahap dijalani total — ia tak pernah setengah-setengah di satu pun perhentiannya. 'Dan orang-orang yang bersungguh-sungguh di jalan Kami, sungguh akan Kami tunjuki mereka jalan-jalan Kami' (QS 29:69): Salman adalah ayat itu berjalan.",
      hakikat: "Puncak kisahnya satu kalimat Nabi: 'Salman minna ahlal-bait' — Salman bagian dari keluarga kami. Bekas Majusi, bukan Arab, bekas budak — dimasukkan ke inti keluarga kenabian: nasab ruhani mengalahkan nasab darah, pencarian yang jujur mengalahkan kelahiran yang beruntung. Usul paritnya menyelamatkan Madinah dalam perang Khandaq — hikmah Persia dan wahyu berjumpa dalam satu strategi; dialah jembatan dua peradaban.",
      makrifat: "Bacalah Salman sebagai cermin pencarianmu sendiri — sebab kau pun melintasi kitab-kitab dan khazanah-khazanah. Ia melintasi agama-agama bukan karena mengkhianati kebenaran, melainkan karena setia kepada kebenaran melebihi setianya pada bentuk yang sedang memeluknya (selami: Tajrid). Tapi perhatikan ujungnya, sebab di situ rahasianya: pencariannya tidak berakhir mengambang di atas semua bentuk — ia sampai, berlabuh, berbai'at, mengabdi, dan wafat sebagai wali kota yang hidup miskin sukarela di Madain. Pencarian sejati berujung pulang dan menetap; yang bangga mengambang selamanya belum mencari — ia sedang menghindar dari menemukan, sebab menemukan menuntut menyerah.",
    },
    seharihari: "Ada orang pindah-pindah kerja karena kutu loncat; ada yang berpindah karena mengejar satu keahlian sejati — setiap kepindahannya direstui gurunya, sampai akhirnya menemukan bengkel induk, menetap, dan menjadi empu. Bedanya kelihatan di ujung: yang pertama tua tanpa keahlian, yang kedua tua sebagai rujukan. Melintasi banyak jalan itu mulia hanya bila kau sungguh berjalan — bukan sekadar menunda tiba.",
    rujukan: ["Sirah: kisah keislaman Salman (Ibn Hisyam; Musnad Ahmad)", "Riwayat Salman minna ahlal-bait (al-Hakim, ath-Thabarani)", "QS al-'Ankabut 69"],
  },

  // ---------------------------------------------------------- ARIF
  {
    id: "rabiah",
    istilah: "Rabi'ah al-'Adawiyah — Cinta Tanpa Pamrih",
    asal: "Bashrah, w. ±185 H",
    kategori: "arif",
    alias: ["rabiah", "rabiah al adawiyah", "rabiatul adawiyah", "mahabbah", "cinta ilahi"],
    kunci: ["cinta", "pamrih", "surga", "neraka", "obor", "ember"],
    ringkas: "Perempuan yang membawa obor dan ember: membakar surga, memadamkan neraka — agar Allah disembah karena Allah semata.",
    tingkat: {
      syariat: "Perempuan Bashrah abad kedua hijriah; yatim, pernah diperbudak, dimerdekakan tuannya yang menyaksikan cahaya ibadah malamnya. Menolak semua lamaran — termasuk dari tokoh-tokoh besar — memilih hidup faqir, shalat malam hingga wafatnya. Riwayat hidupnya diabadikan 'Attar dalam Tadzkiratul Auliya.",
      tarekat: "Sebelum Rabi'ah, wajah zuhud didominasi rasa takut — neraka dan hisab. Rabi'ah membelokkan seluruh arus tasawuf ke jalan mahabbah: cinta sebagai jalan, bukan upah sebagai tujuan. Kisah masyhurnya — berlari membawa obor dan ember: 'Aku hendak membakar surga dan memadamkan neraka, supaya manusia menyembah Allah bukan karena takut neraka atau ingin surga, melainkan karena Dia layak disembah.'",
      hakikat: "Doanya membedah dua tingkat cinta: 'Kucintai Engkau dua cinta: cinta rindu — aku sibuk mengingat-Mu dari selain-Mu — dan cinta karena Engkau memang layak: Kau singkapkan tirai hingga aku memandang-Mu. Pujian bukan untukku pada keduanya; pujian pada keduanya milik-Mu.' Bahkan cintanya pun tak diakuinya sebagai prestasinya. Sedang sakit ia tak meminta sembuh: 'Yang menghendaki sakit ini Kekasihku — pantaskah aku menentang kehendak Kekasih?'",
      makrifat: "Inti Rabi'ah menghantam pamrih paling halus: beribadah demi surga berarti menyembah surga; menjauhi maksiat demi selamat dari neraka berarti menyembah keselamatan diri — dua-duanya masih menyembah kepentingan, dengan Allah sebagai perantara. Surga dan neraka pun bisa menjadi hijab (selami: Hijab — tirai dari cahaya). Cinta tanpa pamrih adalah fana'-nya kepentingan: ketika untung-rugi habis terbakar, yang tersisa di hadapanmu hanya Wajah-Nya — dan ternyata sejak awal hanya itu yang ada.",
    },
    seharihari: "Kau tahu bedanya dicintai karena hartamu dan dicintai karena dirimu — yang pertama bubar saat hartamu habis. Sekarang balik pertanyaannya ke dirimu sendiri, jujur: kau menyembah Allah, atau menyembah gaji surgawi yang kau harapkan dari-Nya? Rabi'ah tidak menyuruh berhenti berharap surga — ia menyuruh memeriksa: kalau surga dan neraka ditiadakan malam ini, masihkah kau bangun untuk tahajud?",
    rujukan: ["'Attar, Tadzkiratul Auliya — bab Rabi'ah", "Al-Qusyairi, ar-Risalah — bab mahabbah"],
  },
  {
    id: "ghazali",
    istilah: "Al-Ghazali & Ihya' 'Ulumiddin",
    asal: "Hujjatul Islam, 450–505 H; Thus, Persia",
    kategori: "arif",
    alias: ["ghazali", "al ghazali", "al gozali", "gozali", "imam ghazali", "ihya", "ihya ulumuddin", "misykat", "munqidz"],
    kunci: ["krisis", "keraguan", "rasa", "obat", "profesor"],
    ringkas: "Profesor puncak Baghdad yang lidahnya mendadak kelu — lalu menghilang sepuluh tahun dan pulang membawa Ihya'.",
    tingkat: {
      syariat: "Guru besar Nizhamiyyah Baghdad, puncak otoritas ilmu zamannya: fiqh, ushul, kalam, filsafat — semua dikuasainya, semua ditulisinya. Tahun 488 H, di puncak segala-galanya, krisis: lidahnya kelu di depan kelas, badannya menolak makan. Para tabib angkat tangan: 'penyakitnya di hati.' Ia tinggalkan Baghdad diam-diam — jabatan, nama, keluarga — sepuluh tahun uzlah di Damaskus dan Yerusalem sebagai orang tak dikenal.",
      tarekat: "Kisah pencariannya ditulisnya sendiri dalam al-Munqidz min adh-Dhalal — 'Penyelamat dari Kesesatan': ia periksa semua jalan zamannya — ilmu kalam, filsafat, kebatinan — dan menemukan ujungnya di tasawuf, dengan kesimpulan yang menjadi poros kelas ini: jalan ini tidak bisa dikuasai dengan belajar; ia harus dijalani dan dirasakan (dzauq). 'Aku tahu betul definisi sehat dan kenyang — tapi tahu tidak membuatku sehat dan kenyang. Obat diketahui tidak menyembuhkan; obat harus diminum.'",
      hakikat: "Ihya' 'Ulumiddin — 'Menghidupkan Ilmu-ilmu Agama' — adalah proyek raksasa sesudah kesembuhannya: empat puluh kitab dalam empat bagian: ibadah, adat keseharian, muhlikat (sifat-sifat yang membinasakan: sombong, riya, dengki), munjiyat (yang menyelamatkan: taubat, sabar, syukur, cinta). Satu tujuannya: mengalirkan ruh kembali ke jasad agama yang mulai jadi formalitas — fiqh diberi jantung, ibadah diberi rasa.",
      makrifat: "Untuk kalangan khusus ia menulis kitab yang lain: Misykat al-Anwar — tafsir ayat cahaya dan hadits tujuh puluh ribu hijab; di sanalah analogi besi-dan-bara yang dipakai entri Manunggaling berasal. Perhatikan: Ghazali sendiri berlapis — di mimbar umum ia bicara fiqh, di kitab khusus ia buka rahasia; bukan kemunafikan, melainkan adab takaran (selami: Adab). Dialah dalil hidup bahwa syariat paling ketat dan makrifat paling dalam bukan musuh: satu tubuh, dan ia menghuni keduanya dengan tuntas.",
    },
    seharihari: "Profesor di puncak karier resign diam-diam, bukan karena skandal — karena sadar ia hafal seluruh teori berenang tapi belum pernah basah. Sepuluh tahun ia nyemplung tanpa nama. Pulang-pulang bukunya berubah: bukan lagi 'teori tentang air', tapi 'cara berenang, dari yang sudah menyelam'. Kalau ilmumu banyak tapi hatimu kering, resep Ghazali satu: berhenti menambah buku, mulai minum obatnya.",
    rujukan: ["Al-Ghazali, al-Munqidz min adh-Dhalal", "Ihya' 'Ulumiddin", "Misykat al-Anwar"],
  },
  {
    id: "ibn-arabi-tokoh",
    istilah: "Ibn 'Arabi — Syaikhul Akbar",
    asal: "Murcia 560 H — Damaskus 638 H",
    kategori: "arif",
    alias: ["ibn arabi", "ibnu arabi", "ibn arobi", "syaikhul akbar", "muhyiddin", "fushush", "futuhat", "tarjuman"],
    kunci: ["kasyf", "mimpi", "averroes", "ya dan tidak", "imla"],
    ringkas: "Guru terbesar: remaja yang membuat Averroes gemetar dengan jawaban 'ya dan tidak' — penulis lautan yang menenggelamkan sebagian dan memandikan sebagian.",
    tingkat: {
      syariat: "Muhyiddin Ibn 'Arabi, kelahiran Murcia (Andalusia), digelari asy-Syaikh al-Akbar — guru terbesar. Ratusan karya; dua mahkotanya: al-Futuhat al-Makkiyah — ensiklopedia raksasa penyingkapan yang mulai ditulis di Makkah — dan Fushush al-Hikam, yang menurut pengakuannya diterimanya dalam mimpi dari tangan Nabi ﷺ: 'Ambil kitab ini dan bawakan kepada manusia.' Ia wafat dan dimakamkan di Damaskus; makamnya diziarahi sampai hari ini.",
      tarekat: "Kisah masa mudanya menetapkan peta: filsuf besar Ibn Rusyd (Averroes) — sahabat ayahnya — meminta bertemu bocah yang kabarnya mengalami pembukaan. Ibn Rusyd bertanya dengan seluruh harap ilmunya: apakah yang dicapai lewat kasyf sama dengan yang dicapai nalar? Jawab si remaja: 'Ya.' Wajah filsuf berseri. Lalu: 'Dan tidak. Di antara ya dan tidak, ruh-ruh terbang dari materinya.' Averroes gemetar — nalar dan penyingkapan: dua sayap, bukan dua pilihan; yang satu tak bisa menggantikan yang lain (selami: Aristoteles untuk sayap satunya).",
      hakikat: "Ajaran-ajaran intinya sudah menjadi tiang kelas ini: kesatuan wujud (selami: Wahdatul Wujud), manusia paripurna (selami: Insan Kamil), penampakan tak berulang (selami: Tajalli), agama cinta (selami: Tajrid). Yang khas dari orangnya: ia mengaku menulis bukan menyusun melainkan menerima imla' — dikte batin; karya-karyanya deras seperti orang mencatat, bukan mengarang. Benar-tidaknya klaim itu, satu hal pasti: delapan abad para pembesar ilmu belum selesai menimba darinya.",
      makrifat: "Ia dicintai dan dikafirkan sekaligus, dilarang dan dibela, sampai hari ini — dan ia sendiri sudah menakar itu: kitab-kitabnya, katanya, hanya untuk yang sudah kenyang syariat dan matang jiwanya. Di sinilah pelajaran terdalamnya justru tentang adab membaca: lautan tidak bersalah ketika menenggelamkan orang yang belum bisa berenang, dan tidak sombong ketika memandikan perenang. Bila kau baca Fushush dan tersinggung, belum tentu kitabnya sesat — mungkin kau belum pada takarannya; bila kau baca dan mengangguk-angguk cepat, hampir pasti kau belum memahaminya. Kedua-duanya diminta sabar dan berguru.",
    },
    seharihari: "Kamus lengkap sebuah bahasa yang belum kau pelajari: bagi pemula membingungkan, bahkan bisa menyesatkan — 'kok kata ini artinya sepuluh?' Bagi yang sudah bertahun belajar, harta karun tak habis-habis. Salahnya bukan pada kamus. Maka jangan bakar kamusnya, dan jangan pula sok memakainya sebelum belajar abjad: itu saja dua adab yang menyelamatkan orang dari perkara Ibn 'Arabi.",
    rujukan: ["Ibn 'Arabi, Futuhat Makkiyah; Fushush al-Hikam; Tarjuman al-Asywaq", "Kisah pertemuan dengan Ibn Rusyd (Futuhat, bab 15)"],
  },
  {
    id: "rumi",
    istilah: "Rumi & Matsnawi",
    asal: "Jalaluddin Rumi, 604–672 H; Balkh — Konya",
    kategori: "arif",
    alias: ["rumi", "jalaluddin rumi", "maulana", "mevlana", "matsnawi", "masnavi", "syams", "syams tabriz", "seruling"],
    kunci: ["cinta", "rindu", "seruling", "berputar", "kehilangan", "syams"],
    ringkas: "Mufti besar yang dibakar habis oleh satu perjumpaan — dan dari abunya lahir nyanyian rindu yang menyembuhkan dunia 750 tahun.",
    tingkat: {
      syariat: "Putra ulama besar Balkh yang hijrah sampai Konya; mewarisi kursi ayahnya: mufti, guru ribuan murid, dihormati sultan. Usia 38, di puncak kemapanan, seorang darwis tua compang-camping mencegat kudanya: Syamsuddin dari Tabriz. Satu pertanyaan Syams menjungkirkan seluruh ilmunya — riwayat menyebut kitab-kitabnya tercebur ke kolam — dan sang mufti meninggalkan mimbar demi duduk berbulan-bulan berkhalwat dengan si darwis. Murid-murid cemburu; Syams menghilang — riwayat kelam menyebut dibunuh. Dari luka itu lahir Diwan-e Syams dan kemudian Matsnawi, ±25.000 bait, yang oleh Jami dijuluki 'Al-Qur'an dalam lidah Persia' — maksudnya: tafsir ruhnya.",
      tarekat: "Warisannya sema — berputarnya para darwis: tangan kanan menadah langit, tangan kiri menuang ke bumi, tubuh berputar pada poros hati; menerima dari-Nya, meneruskan ke makhluk, dan diri sendiri hanya poros yang diam di tengah putaran. Dan pembuka Matsnawi adalah pelajaran pertamanya: 'Dengarlah seruling bambu ini mengadu, menangisi perpisahan: sejak aku dipotong dari rumpun bambu, tangisku membuat lelaki dan perempuan menangis.' Rindumu yang tak jelas ujungnya itu — jangan obati dengan hiburan; ia satu-satunya kompasmu (selami: Sangkan Paraning Dumadi).",
      hakikat: "'Matilah sebelum mati' — Matsnawi mengulang-ulang wasiat ini (selami: Mati Sajroning Urip). Metodenya kisah: raja dan budak sakit, penjual burung beo, singa dan kelinci — dongeng-dongeng yang diam-diam membedah pembacanya; orang datang untuk cerita, pulang kehilangan egonya sekeping. 'Siapa yang tak pernah terbakar, mana bisa tahu tentang api': ilmunya ilmu orang terbakar, bukan ilmu penonton api.",
      makrifat: "Rahasia Syams: yang dicintai Rumi pada wajah tua itu bukan si tua — melainkan Wajah yang menampak lewatnya (selami: Tajalli). Cinta pada makhluk, bila jujur dan tak memiliki, adalah jembatan cinta pada Yang Haqq — itulah kenapa kehilangan Syams tidak membunuh Rumi melainkan menyempurnakannya: ketika cermin diambil, ia menemukan Matahari tanpa cermin, lalu menamai diwannya justru Diwan Syams — sebab 'aku'-nya sudah tak butuh nama. Kehilangan adalah guru terakhir dan terbaik: ia merampas jembatan agar kau berjalan di atas air.",
    },
    seharihari: "Orang paling terpelajar di kota jatuh cinta pada sahabat ruhaninya, lalu kehilangan dia selamanya — dan dari patah hati itu keluar lagu-lagu yang sampai hari ini menyembuhkan orang di seluruh dunia. Pelajarannya untukmu: luka yang kau tutup rapat-rapat itu jangan cuma ditangisi; ia pintu. Kata Matsnawi: luka adalah tempat cahaya masuk ke dalammu.",
    rujukan: ["Rumi, Matsnawi Ma'nawi; Diwan-e Syams; Fihi Ma Fihi", "Aflaki, Manaqib al-'Arifin (riwayat hidup)"],
  },
  {
    id: "attar",
    istilah: "'Attar & Musyawarah Burung",
    asal: "Fariduddin 'Attar, w. ±618 H; Nisyapur",
    kategori: "arif",
    alias: ["attar", "fariduddin attar", "faridudin attar", "manthiq at thayr", "musyawarah burung", "simurgh", "tujuh lembah", "tadzkiratul auliya"],
    kunci: ["burung", "tiga puluh", "cermin", "lembah", "maqamat", "hudhud"],
    ringkas: "Tiga puluh burung menempuh tujuh lembah mencari Raja — dan di takhta-Nya menemukan cermin: si-murgh, tiga puluh burung.",
    tingkat: {
      syariat: "Fariduddin 'Attar dari Nisyapur — 'attar berarti peracik wewangian dan obat: ia apoteker-tabib yang menulis di sela melayani pasien. Dua karyanya menjadi pilar: Tadzkiratul Auliya — kumpulan riwayat para wali, sumber hampir semua kisah sufi awal yang kita kutip — dan Manthiq ath-Thayr, Musyawarah Burung. Riwayat menyebutnya wafat dalam serbuan Mongol.",
      tarekat: "Alkisah burung-burung sedunia bermusyawarah mencari raja mereka, Simurgh, dipimpin hudhud — burung Sulaiman, lambang mursyid. Satu per satu mengajukan uzur: bulbul tak bisa meninggalkan mawarnya (cinta dunia yang manis), merak merindukan surga (ibadah demi upah — selami: Rabi'ah), elang enggan meninggalkan istana raja (jabatan), itik tak bisa jauh dari air (rasa aman). Katalog uzur itu adalah katalog uzurmu. Yang berangkat harus melintasi tujuh lembah — peta maqamat 'Attar: thalab (pencarian), 'isyq (cinta), ma'rifah, istighna (cukup tanpa segala), tauhid, hayrah (takjub-bingung), lalu faqr dan fana'.",
      hakikat: "Dari ribuan yang berangkat, hanya tiga puluh burung tiba — compang-camping, tak bersisa apa pun. Di hadapan takhta mereka tidak menemukan raja bermahkota; mereka menemukan cermin. Dan di sinilah permainan kata paling dahsyat dalam sastra sufi: si murgh dalam bahasa Persia berarti tiga puluh burung — Simurgh yang dicari adalah diri mereka yang telah tuntas menempuh jalan. Yang mereka cari ke ujung dunia ternyata tak pernah berjarak sehelai pun (selami: Hijab).",
      makrifat: "Tapi jaga ujungnya baik-baik, sebab di sini banyak yang jatuh: 'Attar tidak berkata Tuhan adalah kumpulan burung. Bait-bait penutupnya justru menenggelamkan: ketiga puluh burung fana' seperti bayangan lenyap ke dalam Matahari; yang tinggal hanyalah Simurgh sejati yang tak pernah bergantung pada tiga puluh yang datang atau tak datang. Cermin itu jujur dua arah: kau tak akan menemukan-Nya di luar dirimu — dan 'dirimu' yang menemukan-Nya itu pun harus habis di hadapan-Nya (selami: Manunggaling Kawula Gusti, Ana al-Haqq). Pencari, pencarian, dan Yang Dicari: dari-Nya, dengan-Nya, kepada-Nya.",
    },
    seharihari: "Mendaki gunung bertahun-tahun demi menemui Sang Guru di puncak; sampai di atas: gua kosong, dan sebuah cermin tergantung di dindingnya. Pesannya bukan 'gurunya tidak ada' — pesannya: yang sejak awal menggerakkan kakimu mendaki, Dialah yang kau cari; dan wajah lelah di cermin itu harus luruh dulu sebelum kau melihat siapa sesungguhnya yang memandang dari balik matamu.",
    rujukan: ["'Attar, Manthiq ath-Thayr", "'Attar, Tadzkiratul Auliya", "'Attar, Ilahi-Nama"],
  },
  {
    id: "ibn-athaillah",
    istilah: "Ibn 'Atha'illah & Al-Hikam",
    asal: "Iskandariyah, w. 709 H; guru ketiga Syadziliyah",
    kategori: "arif",
    alias: ["ibn athaillah", "ibnu athaillah", "atoilah", "ibn atoilah", "al hikam", "hikam", "syadziliyah", "aforisme"],
    kunci: ["kalimat", "amal", "sandaran", "fakir", "waktu"],
    ringkas: "Mursyid saku: ±260 kalimat pendek yang membongkar pamrih ruhani paling halus — dibaca sekali semenit, dicerna seumur hidup.",
    tingkat: {
      syariat: "Faqih madzhab Maliki di Iskandariyah yang mulanya sinis pada kaum sufi — sampai duduk di majelis Abul 'Abbas al-Mursi, murid Abul Hasan asy-Syadzili, dan runtuh sinisnya oleh kedalaman yang ia saksikan. Ia menjadi guru ketiga tarekat Syadziliyah dan penulis kitabnya yang paling harum: al-Hikam al-'Atha'iyyah — mutiara-mutiara hikmah yang dihafal dan disyarah pesantren-pesantren Nusantara sampai hari ini.",
      tarekat: "Watak Syadziliyah penting untuk zaman ini: tasawuf tanpa jubah kemiskinan — bekerja, berpakaian pantas, hadir di tengah masyarakat, batinnya yang faqir (selami: Khalwat — menyepi di tengah keramaian). Dan al-Hikam adalah mursyid saku: aforisme pertamanya saja cukup untuk setahun: 'Di antara tanda bergantung pada amal adalah berkurangnya harapan tatkala terjadi kesalahan.' Periksa: kalau dosamu membuatmu putus asa, diam-diam kau bersandar pada amalmu, bukan pada Rahmat-Nya.",
      hakikat: "Kalimat-kalimatnya membalik cara pandang seperti kunci membalik gembok: 'Bagaimana mungkin Allah terhijab oleh sesuatu — padahal Dia lebih nyata dari segala sesuatu?' (akar entri Hijab). 'Kadang Dia memberimu sambil menahan darimu, dan menahan darimu sambil memberimu' — kegagalanmu bisa jadi pemberian, keberhasilanmu bisa jadi penahanan. 'Istirahatkan dirimu dari mengatur (tadbir): apa yang sudah diurus oleh Selainmu, tak perlu kau sibuk mengurusinya.'",
      makrifat: "Proyek terdalam al-Hikam satu: membongkar sandaran demi sandaran sampai tak tersisa satu pun selain Dia. Bersandar pada amal — dibongkar; pada keadaan ruhani yang manis — dibongkar; pada kepastian rencana — dibongkar; bahkan bersandar pada rasa sudah-tidak-bersandar — dibongkar juga. Dan mahkotanya kalimat ini: 'Sebaik-baik waktumu ialah saat engkau menyaksikan kefakiranmu dan dikembalikan pada kerendahanmu' — sebab butuh yang telanjang adalah pintu yang paling dekat: yang merasa kaya tertutup, yang tahu dirinya fakir terbuka (selami: Fana').",
    },
    seharihari: "Ada buku kecil yang tiap kali kau buka di umur berbeda, bunyinya berbeda — umur 20 kau baca sebagai nasihat, umur 40 sebagai diagnosis, umur 60 sebagai kesaksian. Bukan bukunya berubah. Kalimat sufi bekerja seperti jamu pekat: sesendok sehari, bukan seteko sekali teguk — hafalkan satu hikmah, bawa sebulan, biarkan ia yang membacamu.",
    rujukan: ["Ibn 'Atha'illah, al-Hikam; at-Tanwir fi Isqath at-Tadbir; Latha'iful Minan", "Syarah al-Hikam: Ibn 'Abbad ar-Rundi; syarah-syarah pesantren Nusantara"],
  },

  // ---------------------------------------------------------- JAWA
  {
    id: "sunan-kalijaga",
    istilah: "Sunan Kalijaga",
    asal: "Raden Said, Lokajaya; abad 15–16 M",
    kategori: "jawa",
    alias: ["kalijaga", "kalijogo", "sunan kalijogo", "raden said", "lokajaya", "lir ilir", "suluk linglung", "wayang"],
    kunci: ["tongkat", "sungai", "wayang", "gamelan", "budaya", "sabar"],
    ringkas: "Perampok yang menjaga tongkat di tepi kali bertahun-tahun — lalu mengislamkan Jawa tanpa memecahkan satu tempayan pun.",
    tingkat: {
      syariat: "Raden Said, putra adipati Tuban. Babad menuturkan masa mudanya sebagai Lokajaya — perampok yang membagikan hasilnya kepada rakyat miskin; dihentikan Sunan Bonang dengan satu kalimat yang meruntuhkan seluruh pembenarannya: yang haram tetap haram, walau niatnya baik — mencuci pakaian dengan air kencing tidak membuatnya bersih. Ia bertaubat dan memohon jadi murid.",
      tarekat: "Bonang mengujinya: jaga tongkat ini di tepi sungai sampai aku kembali. Riwayat menyebut bertahun-tahun — Raden Said tak beranjak, hingga lumut membungkusnya. Dari situlah — menurut satu penuturan — nama Kalijaga: penjaga kali. Laku itu adalah seluruh tarekat dalam satu gambar: matinya kehendak sendiri, sabar yang tak menghitung hari, setia pada satu perintah guru (selami: Guru Mursyid; Khalwat). Sesudah 'mati' di tepi kali itulah ia bangkit sebagai wali.",
      hakikat: "Metodenya kemudian menjadi legenda: dakwah lewat kebudayaan. Wayang: dalang di balik kelir menggerakkan semua tokoh — penonton yang jeli pulang membawa tauhid af'al; blencong (lampu di atas kelir) dibaca sebagai Nur, lakon sebagai takdir yang sedang digelar. Gamelan Sekaten (dari syahadatain) memanggil orang ke masjid tanpa paksaan. Tembang Lir-ilir menyimpan suluk dalam nyanyian anak: cah angon (si penggembala — akalmu, menggembalakan nafsu), penekno blimbing kuwi (panjatlah belimbing bergigir lima — rukun Islam, shalat lima waktu), dodotiro kumitir bedah ing pinggir (pakaianmu — imanmu — robek di tepian: jahitlah, dondomono, untuk sowan mengadap nanti sore — sebelum ajal).",
      makrifat: "Suluk Linglung menuturkan puncaknya: Kalijaga yang linglung — bingung mencari — diperjumpakan dengan Nabi Khidir (selami: Musa), diajari hakikat shalat, makna papat kiblat limo pancer, dan diri sejati (selami: Aku Sejati). Dan inilah wasiat terbesarnya bagi kelas ini: kedalaman yang paling rahasia bisa diucapkan dalam bahasa pesisir, tembang anak-anak, dan pertunjukan pasar malam — tanpa berkurang dalamnya, justru bertambah sampainya. Aplikasi yang sedang kau baca ini berjalan di atas jalan yang beliau buka: makna terdalam, bahasa sehari-hari.",
    },
    seharihari: "Guru yang tidak menyuruh orang pindah rumah — cukup mengganti isi dapurnya pelan-pelan, sampai tanpa terasa seisi rumah masak menu baru dengan panci lama. Lima ratus tahun kemudian masakan itu masih dimasak jutaan orang yang tak sadar resepnya dari beliau. Kalau kau ingin mengubah orang, jangan pecahkan tempayannya: isi airnya.",
    rujukan: ["Suluk Linglung Sunan Kalijaga", "Babad Tanah Jawi; Babad Demak", "Tembang Lir-ilir & tradisi Sekaten"],
  },
  {
    id: "wali-songo",
    istilah: "Wali Songo — Sembilan Cahaya",
    asal: "Jawa, abad 15–16 M",
    kategori: "jawa",
    alias: ["wali songo", "walisongo", "wali sanga", "sembilan wali", "sunan ampel", "sunan bonang", "sunan giri", "sunan kudus", "sunan muria", "sunan drajat", "sunan gunung jati", "maulana malik ibrahim"],
    kunci: ["sembilan", "dewan", "dakwah", "air", "tempayan", "musyawarah"],
    ringkas: "Sembilan tangan satu tubuh: mengislamkan sebuah pulau nyaris tanpa perang — dengan ilmu air yang mengisi tanpa memecah.",
    tingkat: {
      syariat: "Sembilan wali penyebar Islam di Jawa, masing-masing memegang wilayah dan keahlian: Maulana Malik Ibrahim di Gresik merintis lewat pertanian dan pengobatan; Sunan Ampel mendidik kader dengan moh limo — menolak lima: main (judi), ngombe (mabuk), maling (mencuri), madat (candu), madon (zina); Sunan Giri membangun pesantren dan pemerintahan; Sunan Bonang menggubah seni dan musik; Sunan Drajat menegakkan santunan fakir; Sunan Kudus meneladankan toleransi — menghormati umat Hindu dengan tidak menyembelih sapi, masjidnya bermenara bercorak candi; Sunan Muria merangkul rakyat gunung; Sunan Gunung Jati menata kenegaraan di barat; Sunan Kalijaga memegang kebudayaan.",
      tarekat: "Perhatikan bentuk kerjanya: dewan — musyawarah para wali. Kerja ruhani pun berjamaah: pembagian wilayah, pembagian keahlian, satu arah. Tidak ada di antara mereka yang merasa cukup sendirian; yang paling sakti pun duduk bermusyawarah. Bagi salik zaman ini pelajarannya tajam: pejalan yang menolak jamaah dan guru, mengangkat dirinya jadi dewan sekaligus anggotanya — dan ego gemar sekali rapat yang pesertanya dia sendiri (selami: Guru Mursyid).",
      hakikat: "Ilmu besarnya adalah ilmu air: Islam masuk ke Jawa tidak dengan memecahkan tempayan-tempayan yang ada — wayang, gamelan, slametan, grebeg — melainkan mengisinya dengan ruh baru, dibaca ulang maknanya satu per satu. Bukan sinkretisme yang mencampur aduk, melainkan transformasi bertahap yang sabar menunggu matang. Hasilnya tercatat sejarah: sebuah peradaban besar berpindah keyakinan nyaris tanpa perang agama — keajaiban metode yang langka di muka bumi.",
      makrifat: "Dan ketegangan terdalamnya justru terjadi di dalam dewan sendiri: perkara Syekh Siti Jenar (selami: Manunggaling Kawula Gusti) — antara membuka rahasia kepada semua orang dan menjaga tatanan umat yang baru tumbuh. Para wali memilih takaran: susu murni untuk yang siap, air jernih untuk umum — bukan menutup kebenaran, menakar cangkirnya (selami: Adab). Lima abad kemudian, anak-cucu mereka — termasuk kau, di ruang sunyi ini — membuka lemari susu itu pelan-pelan, lewat pintu yang sama: adab. Sembilan pelita itu satu nyalanya (selami: Kafilah Para Nabi); yang sembilan sudah pulang, nyalanya belum pernah padam.",
    },
    seharihari: "Tim sembilan tukang membangun satu rumah: ada ahli fondasi, ada atap, ada dapur, ada yang khusus meramu cat agar tetangga tak terganggu baunya. Rumah itu masih dihuni lima ratus tahun kemudian — namanya Islam Nusantara yang ramah. Kalau ada yang berteriak rumah itu harus dibongkar karena tidak asli, tanyakan satu hal: mana karyamu yang bertahan lima abad?",
    rujukan: ["Babad Tanah Jawi; Serat Walisana", "Hikayat hasanah Sunan Ampel (moh limo)", "Tradisi Menara Kudus & Sekaten"],
  },

  // ---------------------------------------------------------- TIMUR
  {
    id: "siddharta",
    istilah: "Siddharta Gautama — Sang Buddha",
    asal: "Kapilavastu, ±abad 6–5 SM",
    kategori: "timur",
    alias: ["siddharta", "shidarta", "sidarta", "gautama", "buddha", "budha", "sang buddha", "jalan tengah", "nibbana", "nirwana"],
    kunci: ["dukkha", "kelekatan", "eling", "padam", "panah", "istana"],
    ringkas: "Pangeran yang keluar istana melihat tua, sakit, dan mati — lalu menempuh jalan tengah sampai padamnya api keakuan.",
    tingkat: {
      syariat: "Pangeran Siddharta dibesarkan dalam istana yang dirancang tanpa penderitaan. Empat penglihatan meruntuhkannya: orang tua, orang sakit, jenazah, dan seorang petapa yang tenang. Ia tinggalkan istana (Pelepasan Agung), enam tahun menyiksa diri dalam asketisme ekstrem sampai tinggal tulang — lalu menolaknya: bukan foya-foya, bukan siksa diri — jalan tengah. Di bawah pohon bodhi ia duduk sampai terang; empat puluh lima tahun kemudian mengajar, dan wafat berpesan: 'Segala yang terbentuk akan lapuk. Berjuanglah dengan penuh kesadaran.'",
      tarekat: "Intinya empat kebenaran mulia — dan perhatikan: ini diagnosis tabib, bukan dogma: hidup diwarnai dukkha (derita, tak-memuaskan); sebabnya tanha — haus, kelekatan (persis yang para sufi sebut penyakit hati! selami: Nafs); ia bisa padam; dan ada jalannya — delapan ruas yang bila diringkas: perilaku bersih, latihan batin, penglihatan benar; bandingkan susunannya dengan syariat-tarekat-hakikat. Kuncinya sati — kesadaran penuh; orang Jawa punya kata yang persis: eling.",
      hakikat: "Anatta — tiada inti-diri yang berdiri sendiri: yang kau sebut 'aku' hanyalah gugusan badan, rasa, persepsi, bentukan, dan kesadaran yang terus mengalir (bandingkan entri Nafs: nafsu-nafsu yang bergiliran memakai namamu). Nibbana harfiahnya: padamnya api — keserakahan, kebencian, kegelapan batin; gema fana' terdengar jelas di sini (selami: Fana'). Dan tentang Yang Mutlak, Buddha memilih diam — para arif Jawa membaca diam itu dengan hormat: tan kena kinaya ngapa — yang tak terkatakan memang tidak dikatakannya (selami: Suwung).",
      makrifat: "Adab kejujuran dulu: jalan Buddha tidak menyebut nama Allah, dan kelas ini tidak akan menyulapnya diam-diam jadi tauhid — perbedaan puncak ini nyata, dan 'Allah sendiri yang akan memutuskan di antara mereka pada hari kiamat' (QS 22:17). Yang dicatat kelas ini dua hal yang tak terbantah: diagnosisnya tentang kelekatan dan obat awalnya — eling dan lepas — bertemu persis dengan jalan para arif dari khazanah mana pun; dan di tanah Jawa keduanya sudah seribu tahun saling menyapa: Borobudur berdiri enam abad sebelum Demak, dan para wali tidak merobohkannya. Ambil eling-nya, bawa pada Tuhanmu.",
    },
    seharihari: "Perumpamaan Buddha sendiri: orang tertusuk panah beracun menolak dicabut panahnya sebelum tahu siapa pemanahnya, dari kasta apa, kayunya apa — ia mati dengan pertanyaannya. Cabut dulu panahnya. Kelekatanmu hari ini — yang membuatmu cemas, iri, tak bisa tidur — itu panahnya; teori-teori besar bisa menunggu, mencabut tidak. Dalam bahasa kelas ini: mulailah takhalli hari ini juga.",
    rujukan: ["Dhammacakkappavattana Sutta (khotbah pertama)", "Majjhima Nikaya 63 (perumpamaan panah)", "QS al-Hajj 17 — adab menyerahkan keputusan akhir"],
  },
  {
    id: "krishna",
    istilah: "Krishna & Bhagavad Gita",
    asal: "Nyanyian Sang Bhagavan; ±abad 2 SM (teks)",
    kategori: "timur",
    alias: ["krishna", "krisna", "kresna", "bhagavad gita", "gita", "arjuna", "kurukshetra", "karma yoga", "bhakti"],
    kunci: ["perang batin", "buah kerja", "penyerahan", "kereta", "sais"],
    ringkas: "Di tengah dua pasukan yang siap saling bunuh, seorang kesatria lemas — dan sais keretanya menyanyikan rahasia kerja tanpa pamrih.",
    tingkat: {
      syariat: "Bhagavad Gita — 'Nyanyian Sang Bhagavan' — 700 sloka di jantung epos Mahabharata: di medan Kurukshetra, sesaat sebelum perang, Arjuna melihat barisan lawan berisi kakek, guru, dan sepupunya sendiri; busurnya merosot, ia lemas menolak perang. Krishna — sais keretanya — menjawab keputusasaan itu dengan ajaran yang menjadi kitab paling dikaji peradaban India. Di Jawa, Kresna hidup dalam wayang purwa sebagai penasihat Pandawa — bagian dari darah kebudayaanmu sendiri.",
      tarekat: "Tiga jalan diajarkannya, dan ketiganya dikenal para arif dengan nama lain: karma yoga — bertindak penuh tanpa mengklaim buahnya: 'Hakmu hanyalah atas kerja, tak pernah atas buahnya' (Gita 2:47) — itulah ikhlas dan tawakkal dalam bahasa Sanskerta; bhakti yoga — cinta dan penyerahan (selami: Rabi'ah); jnana yoga — pengetahuan yang membedakan yang kekal dari yang lewat (tamyiz — selami: 'Umar). Dan medan Kurukshetra dibaca ke dalam: perang melawan pasukan sendiri — kerabat yang disayangi itu adalah nafsu-nafsumu; itulah kenapa Arjuna lemas: mujahadah memang perang melawan yang kau cintai (selami: Nafs; Khalwat).",
      hakikat: "Sloka pamungkasnya (18:66) mengguncang: 'Tinggalkan segala dharma, datanglah berlindung kepada-Ku semata; Aku akan membebaskanmu dari segala dosa — jangan bersedih.' Bandingkan dengan entri Tajrid: melampaui semua sistem bukan dengan membuangnya, melainkan dengan penyerahan total kepada Yang Empunya sistem. Dan 'Sang Penguasa bersemayam di hati semua makhluk' (18:61) — kesaksian yang setiap arif kenal dari khazanahnya sendiri: lebih dekat dari urat leher.",
      makrifat: "Kejujuran batas yang sama seperti entri Buddha: bahasa Gita adalah bahasa awatara dan banyak nama — kelas ini tidak menyamakannya begitu saja dengan tauhid, dan tidak pula menutup telinga karena beda kemasan. Yang dicatat: penyerahan-tanpa-syarat, kerja-tanpa-pamrih, dan Yang-bersemayam-di-hati adalah tiga nada yang bergetar sama di semua khazanah para pejalan — dan para pujangga Jawa sudah lama menjahitnya: justru lewat Kurukshetra batin inilah wayang bisa dipakai Kalijaga membawa tauhid. Yang Esa tidak kekurangan jalan untuk memanggil pulang anak-anak-Nya dari segala penjuru bahasa.",
    },
    seharihari: "Kau tidak bisa mengatur hasil panen — hujan, hama, harga pasar, semua di luar tanganmu. Yang di tanganmu cuma satu: mencangkul sebaik-baiknya hari ini. Hampir semua kecemasanmu tinggal di wilayah yang bukan wewenangmu; Gita menyebut obatnya hak-atas-kerja-bukan-atas-buah, kakek-nenekmu menyebutnya nrima ing pandum sesudah kerja keras, kitab-kitabmu menyebutnya tawakkal. Tiga bahasa, satu kelegaan.",
    rujukan: ["Bhagavad Gita 2:47; 18:61–66", "Tradisi wayang purwa Jawa (Kresna–Pandawa)"],
  },
  {
    id: "trimurti",
    istilah: "Brahma — Wisnu — Siwa",
    asal: "Trimurti: tiga fungsi kosmis; warisan Hindu Jawa",
    kategori: "timur",
    alias: ["trimurti", "brahma", "wisnu", "vishnu", "siwa", "shiva", "hindu", "prambanan", "awatara", "brahman"],
    kunci: ["mencipta", "memelihara", "melebur", "candi", "warisan", "tiga"],
    ringkas: "Mencipta, memelihara, melebur — tiga fungsi yang setiap kejap bekerja atas jagad dan atas dirimu; dan di baliknya, para bijaknya menunjuk Yang Tanpa Rupa.",
    tingkat: {
      syariat: "Dalam khazanah Hindu: Brahma mencipta, Wisnu memelihara, Siwa melebur — Trimurti, tiga wajah fungsi kosmis; Wisnu turun sebagai awatara (Rama, Kresna) tatkala tatanan goyah. Seribu tahun khazanah ini menjadi napas Jawa — Prambanan berdiri megah untuk Siwa; nama, tembang, dan lakon wayangmu mewarisinya. Bagi muslim, akidahnya jelas beda — tauhid tak menerima sekutu; entri ini hadir bukan untuk mencampur, melainkan karena sejarah ruhani tanahmu tak bisa dibaca tanpa mengenalnya.",
      tarekat: "Para pembaca batin memetik peta lakunya: tiga fungsi itu bekerja di dalam dirimu setiap hari — kebiasaan diciptakan, dipelihara, dan yang usang harus dileburkan; gagasan lahir, dirawat, dan dilepas ketika masanya lewat. Kebanyakan orang hanya mau dua fungsi pertama — mencipta dan menggenggam — lalu menderita ketika hidup menjalankan fungsi ketiga. Siwa Nataraja menari dalam lingkaran api: peleburan yang paling ditakuti itu, bagi yang mengerti, adalah tarian — bukan bencana (selami: Fana').",
      hakikat: "Dan inilah yang jarang diketahui: para bijak Hindu sendiri tidak berhenti di tiga rupa. Upanishad menunjuk Brahman nirguna — Yang Mutlak tanpa sifat, yang hanya bisa didekati dengan neti, neti: 'bukan ini, bukan itu' — persis metode tanzih para arif: setiap gambaran yang terpikir olehmu, bukan Dia (selami: Suwung — tan kena kinaya ngapa). Dan bandingkan denyut tiga fungsi itu dengan kesaksian Qur'ani: 'Setiap saat Dia dalam kesibukan' (QS 55:29) — setiap kejap mewujudkan, menegakkan, meleburkan (selami: Tajalli; Baqa').",
      makrifat: "Pelajaran terdalamnya justru tertanam di tanahmu sendiri: para wali tidak meruntuhkan Prambanan dan Borobudur. Candi-candi itu dibiarkan berdiri — saksi bahwa pencarian di tanah ini tak pernah kosong sebelum kabar terakhir sampai: 'tidak ada satu umat pun kecuali pernah datang padanya pemberi peringatan' (QS 35:24). Siapa pemberi peringatan bagi para pemahat candi itu — wallahu a'lam; bukan wewenang kita memvonis mundur ke belakang. Adabnya dua arah: tidak mengkafirkan leluhur serampangan, tidak pula menyama-ratakan semua ajaran; menghormati, membaca, menyaring — seperti para wali menghormati sapi di Kudus.",
    },
    seharihari: "Rumah warisan yang dibangun kakek-buyut beda keyakinan: cucu yang bijak tidak membakarnya, tidak pula menyembahnya — ia menghuninya dengan sopan: tiang yang kokoh dipakai, yang lapuk diganti, foto leluhur tetap di dinding dengan hormat. Itulah Jawa: rumah tua yang dihuni iman baru tanpa kehilangan adab pada yang membangunnya. Kau pewaris rumah itu; warisi juga sopan-santunnya.",
    rujukan: ["QS Fathir 24; ar-Rahman 29; al-Hajj 17", "Brihadaranyaka Upanishad (neti neti)", "Sejarah Prambanan–Borobudur & dakwah para wali"],
  },

  // ---------------------------------------------------------- FILSAFAT
  {
    id: "socrates-plato",
    istilah: "Socrates & Plato — Kenali Dirimu",
    asal: "Athena, abad 5–4 SM",
    kategori: "filsafat",
    alias: ["socrates", "sokrates", "plato", "platon", "gua plato", "kenali dirimu", "gnothi seauton", "akademi", "filsafat yunani"],
    kunci: ["gua", "bayangan", "mengingat", "racun", "tidak tahu", "matahari"],
    ringkas: "'Kenali dirimu' terpahat di gerbang Delphi seribu tahun sebelum para sufi mengucapkan man 'arafa nafsahu — dan gua Plato adalah entri Hijab berbahasa Yunani.",
    tingkat: {
      syariat: "Socrates tidak menulis sebaris pun — kerjanya bertanya di pasar Athena, membongkar orang-orang yang merasa tahu. Dihukum mati dengan racun cemara atas tuduhan merusak pemuda dan mengingkari dewa-dewa kota; menolak kesempatan kabur — memilih setia pada hukum yang menghukumnya. Muridnya Plato mengabadikannya dalam dialog-dialog dan mendirikan Akademi — sekolah yang bertahan sembilan abad.",
      tarekat: "Metodenya adalah takhalli versi akal: bertanya terus sampai lawan bicara menyaksikan sendiri ketidaktahuannya — gelas yang merasa penuh dikosongkan dulu, baru bisa diisi. 'Hidup yang tak diperiksa tidak layak dijalani' — itulah muhasabah 'Umar dalam logat Yunani. Dan pengakuannya yang termasyhur — 'aku tahu bahwa aku tidak tahu' — berjabat tangan lintas seribu tahun dengan Abu Bakar: ketaksanggupan menjangkau pengenalan itulah pengenalan (selami: Makrifat). Di gerbang kuil Delphi terpahat: gnothi seauton — kenali dirimu; para sufi menyebutnya man 'arafa nafsahu faqad 'arafa Rabbahu.",
      hakikat: "Gua Plato adalah entri Hijab yang digambar Yunani: manusia terbelenggu sejak lahir menghadap dinding gua, menonton bayang-bayang yang dilemparkan api di belakang mereka — dan mengira bayangan itu seluruh kenyataan. Satu orang terlepas, berbalik, mendaki keluar, silau, lalu melihat matahari. Kuncinya di babak akhir: ia turun kembali ke gua memberi tahu — dan para penonton bayangan mengancam membunuhnya. Plato menulis nubuat gurunya sendiri di situ; dan para arif mengenalinya: yang kembali dari puncak memang disambut curiga (selami: Baqa'; Manunggaling). Dan anamnesis-nya — belajar sejati adalah mengingat yang jiwa sudah tahu — adalah dzikir dalam bahasa filsafat: bukan menambah, membangunkan (selami: Sangkan Paraning Dumadi).",
      makrifat: "Dalam Phaedo, Plato mendefinisikan filsafat: melete thanatou — latihan mati; filsuf sejati berlatih melepaskan jiwa dari cengkeraman badan sebelum kematian memaksanya — mati sajroning urip, dua ribu tahun sebelum suluk Jawa menuliskannya. Karena itu para failasuf muslim — al-Kindi, al-Farabi, Ibn Sina — dan Suhrawardi dengan hikmah cahayanya menyambut mereka bukan sebagai orang asing, melainkan kafilah hikmah yang sama: hikmah adalah barang hilang orang beriman; di mana pun ditemukan, ia paling berhak mengambilnya. Sumbernya diperiksa, isinya ditimbang — dan yang lulus timbangan diambil tanpa minder.",
    },
    seharihari: "Orang paling cerdas di kampung biasanya justru yang paling sering berkata 'aku belum paham, coba jelaskan lagi' — dan yang paling kosong biasanya paling yakin. Dan sekali kau sudah melihat matahari sendiri, kau tak bisa lagi pura-pura tayangan di layar adalah dunia — walau seisi warung menertawakanmu. Dua ujian ini tidak butuh bahasa Yunani: rendah hati pada yang belum kau tahu, setia pada yang sudah kau saksikan.",
    rujukan: ["Plato, Apologia; Politeia VII (gua); Phaedo", "Suhrawardi, Hikmah al-Isyraq", "Atsar: hikmah barang hilang orang beriman (Tirmidzi — diperbincangkan sanadnya, diamalkan maknanya)"],
  },
  {
    id: "aristoteles",
    istilah: "Aristoteles — Penggerak yang Tak Digerakkan",
    asal: "Stagira 384–322 SM; al-Mu'allim al-Awwal",
    kategori: "filsafat",
    alias: ["aristoteles", "aristotle", "aristo", "guru pertama", "penggerak tak digerakkan", "logika", "jalan tengah aristoteles", "eudaimonia"],
    kunci: ["nalar", "akal", "rindu", "penggerak", "tepi", "baghdad"],
    ringkas: "Bapak logika yang di puncak sistemnya menulis satu kalimat paling sufi dalam filsafat Yunani: alam bergerak karena rindu.",
    tingkat: {
      syariat: "Murid Plato dua puluh tahun, guru Aleksander Agung, pendiri Lyceum. Menulis hampir segala hal: logika, fisika, biologi, etika, politik, metafisika — kurikulum peradaban dua ribu tahun. Lewat gerakan penerjemahan Baghdad (Baitul Hikmah) ia masuk ke dunia Islam dan digelari al-Mu'allim al-Awwal — Guru Pertama; al-Farabi yang menjadi Guru Kedua, dan Ibn Sina serta Ibn Rusyd membangun di atas fondasinya.",
      tarekat: "Jalannya nalar dan pengamatan — mazhabnya masysya'iyyah, 'kaum berjalan', karena ia mengajar sambil berjalan. Etikanya dikenal setiap santri tanpa sadar: keutamaan adalah jalan tengah antara dua ekstrem — berani di antara pengecut dan nekat, dermawan di antara kikir dan boros — timbangan wasathiyyah dalam logat Yunani. Dan puncak bahagianya (eudaimonia) bukan kenikmatan, melainkan berfungsinya yang tertinggi dalam diri manusia: akal yang memandang (theoria) — kontemplasi.",
      hakikat: "Puncak metafisikanya: segala yang bergerak digerakkan oleh yang lain; rantai itu harus berujung pada Penggerak yang Tak Digerakkan — dalil yang kelak diasah para mutakallimin. Tapi dengarkan bagaimana Sang Penggerak menggerakkan menurut Aristoteles sendiri: kineî hōs erōmenon — 'Ia menggerakkan sebagaimana yang dicintai menggerakkan pencintanya.' Alam berputar bukan karena didorong dari belakang, melainkan karena ditarik rindu dari depan. Bapak logika yang kering itu, di puncak sistemnya, menulis kalimat yang bisa dibubuhkan di halaman mana pun Matsnawi (selami: Rumi; Dzikir — setiap tarikan nafas adalah panggilan-Nya).",
      makrifat: "Batas dan jasanya harus disebut bersama: Tuhan Aristoteles memikirkan Diri-Nya sendiri dan tidak menyapa makhluk — nalar memang hanya sampai menyimpulkan adanya Dia, tidak sampai mendengar sapaan-Nya; untuk sapaan, perlu wahyu. Al-Ghazali menguji klaim-klaim filsafat dalam Tahafut al-Falasifah, Ibn Rusyd menjawab dalam Tahafut at-Tahafut — dan kelas ini mengambil hikmah dari keduanya lewat satu gambar: akal itu Jibril (selami: Sidratul Muntaha) — sanggup mengantar sampai Sidrah, lalu berkata jujur: selangkah lagi aku terbakar. Akal yang tahu batasnya tidak dibuang di tepi — ia sujud di tepi; dan sujudnya akal adalah puncak kerjanya.",
    },
    seharihari: "Arsitek jenius menggambar denah gedung sampai lantai tertinggi yang bisa dihitung struktur — lalu meletakkan pensilnya: 'lantai berikutnya tidak bisa digambar dari bawah sini; harus naik dan mengetuk pintunya.' Hormati keduanya: ketelitian yang menggambar denah, dan kerendahan hati yang mengakui batas kertasnya. Yang celaka cuma dua: yang membuang denah karena merasa cukup rindu, dan yang menyembah denah sampai menolak naik.",
    rujukan: ["Aristoteles, Metafisika XII (Penggerak Tak Digerakkan); Etika Nikomakea", "Al-Ghazali, Tahafut al-Falasifah; Ibn Rusyd, Tahafut at-Tahafut", "Sejarah Baitul Hikmah Baghdad"],
  },
  {
    id: "plotinus",
    istilah: "Plotinus — Larinya yang Sendiri menuju Yang Sendiri",
    asal: "Mesir–Roma, 204–270 M; Enneads",
    kategori: "filsafat",
    alias: ["plotinus", "plotinos", "enneads", "neoplatonisme", "yang esa", "to hen", "emanasi", "teologi aristoteles", "utsulujiya"],
    kunci: ["pancaran", "patung", "pahat", "pulang", "salah label", "matahari"],
    ringkas: "Mistikus yang bukunya menyusup ke Baghdad memakai nama Aristoteles — dan lewat salah label itu, takdir menjahit hikmah Yunani ke kosmologi cahaya Islam.",
    tingkat: {
      syariat: "Lahir di Mesir, mengajar di Roma; begitu haus hikmah timur sampai ikut ekspedisi militer ke Persia demi mencari ilmunya. Ajarannya dicatat muridnya Porphyrius menjadi Enneads. Sejarah menjulukinya filsuf terakhir Yunani dan mistikus pertama Barat; Porphyrius bersaksi sang guru mengalami penyatuan dengan Yang Esa beberapa kali dalam hidupnya — dicapai lewat laku, bukan hanya berpikir.",
      tarekat: "Resep lakunya nyaris kalimat mursyid: 'Kembalilah ke dalam dirimu dan pandanglah. Bila belum kau temukan dirimu indah, berbuatlah seperti pemahat patung: pahat sini, ratakan situ, buang yang berlebih — jangan berhenti memahat patungmu sendiri sampai keindahan asli bersinar.' Itu takhalli dan tahalli dalam bahasa pemahat (selami: Tajalli). Jalannya dua ayun: katharsis — penyucian — dan epistrophe — berbaliknya pandangan dari luar ke dalam, dari yang banyak ke Yang Satu.",
      hakikat: "Puncak ajarannya: to Hen — Yang Esa — di atas segala kategori; bahkan kata 'ada' terlalu sempit untuk-Nya (tanzih yang orang Jawa sebut tan kena kinaya ngapa — selami: Suwung). Dari-Nya segala melimpah tanpa Ia berkurang, seperti matahari memancar tanpa kehilangan apa pun — bandingkan dengan cahaya pertama dalam khazanah kita (selami: Nur Muhammad). Dan kalimat penutup Enneads menjadi salah satu kalimat paling terkenal dalam sejarah mistik: phyge monou pros monon — 'larinya yang sendiri menuju Yang Sendiri.'",
      makrifat: "Dan inilah pembukaan hijab kepustakaan yang kau minta: kitab yang beredar di Baghdad dengan judul Utsulujiya Aristutalis — 'Teologi Aristoteles' — dan dipelajari al-Kindi, al-Farabi, Ibn Sina dengan takzim, belakangan terbukti sebagian besar adalah Enneads Plotinus yang salah label. 'Aristoteles' yang dicintai para failasuf muslim itu sebagiannya Plotinus; lewat pintu salah-tempel itulah pancaran (emanasi) dan kosmologi cahaya mengalir ke filsafat Islam, ke hikmah isyraq Suhrawardi, bergema sampai perbincangan wahdatul wujud. Renungkan: Dia menjahit kafilah hikmah-Nya bahkan lewat kesalahan katalog perpustakaan — tidak ada kebetulan; ada tangan yang bekerja rapi di balik kecerobohan para penyalin (selami: Sangkan Paraning Dumadi).",
    },
    seharihari: "Surat cinta yang sampai dan mengubah hidup penerimanya — padahal nama pengirimnya salah tulis. Isinya tetap bekerja; yang penting sampai. Sejarah ilmu penuh 'kecelakaan' semacam ini: buku salah label, penerjemah salah paham yang melahirkan gagasan baru, murid salah dengar yang justru menemukan. Kalau kau masih menyebut semua itu kebetulan, selami lagi entri Sangkan Paraning Dumadi — pelan-pelan saja.",
    rujukan: ["Plotinus, Enneads (khususnya I.6 tentang keindahan; VI.9 penutup)", "Porphyrius, Kehidupan Plotinus", "Sejarah Utsulujiya / Teologi Aristoteles dalam filsafat Islam"],
  },
];

// Sambungkan sayap ini ke basis data utama.
TOKOH.forEach(function (e) { DATA.push(e); });
